### ISSUE TITLE
[🚀 Feature]: Recorded Video File Names

### ISSUE THREAD

**Issue by LukeIGS** [SeleniumHQ/selenium#10018]
### Feature and motivation

In the current implementation of grid 4 video recording videos are saved using a file name that's determined at the start of the ffmpeg container while in a start grid configuration.  (Dynamic also works roughly the same way.)

The issue with this is that there's no great way to identify a video named "video.mp4", or even "edge_video.mp4" if one attempts to save that video to a mounted storage of any kind short of using some scripting to rename the generated video from the client side or something (which would be prone to all sorts of race conditions).

My thoughts on a solution for this would be to provide the video name to the video recording container when recording is started by the selenium session, passing the sessions sessionId as the file name.  Since this is visible to the client, it would allow easy linking a video the a given test run on the client side.

### Usage example

Given a static grid where each video container mounts a shared storage directory...
```yaml
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: selenium-chrome-node-deployment
  labels:
    app: selenium-chrome-node
    name: selenium-chrome-node
    component: "selenium-grid-4"
spec:
  replicas: 10
  selector:
    matchLabels:
      app: selenium-chrome-node
  template:
    metadata:
      labels:
        app: selenium-chrome-node
        name: selenium-chrome-node
        component: "selenium-grid-4"
    spec:
      containers:
        - name: video
          image: selenium/video
          resources:
            limits:
              memory: "1Gi"
              cpu: "1"
          volumeMounts:
            - name: video
              mountPath: /video
        - name: selenium
          image: selenium/node-chrome:latest
          env:
            - name: SE_EVENT_BUS_HOST
              value: "selenium-event-bus"
            - name: SE_EVENT_BUS_PUBLISH_PORT
              value: "4442"
            - name: SE_EVENT_BUS_SUBSCRIBE_PORT
              value: "4443"
            - name: VNC_NO_PASSWORD
              value: "true"
            - name: "SE_OPTS"
              value: "--log-level FINE --grid-url https://selenium-grid.example.com"
          ports:
            - containerPort: 5553
              protocol: TCP
            - containerPort: 5555
              protocol: TCP 
          volumeMounts:
            - name: dshm
              mountPath: /dev/shm
          resources:
            requests:
              memory: "1Gi"
              cpu: "1"
            limits:
              memory: "1Gi"
              cpu: "1"
      volumes:
        - name: video
          flexVolume:
            driver: 'fstab/cifs'
            fsType: 'cifs'
            secretRef:
              name: 'selenium-video'
            options:
              networkPath: '//examplefs/qa/selenium-videos'
              mountOptions: 'dir_mode=0777,file_mode=0777,vers=3.0,domain=EXAMPLEDOMAIN'
        - name: dshm
          emptyDir: { "medium": "Memory" }
```

Using ruby:
```ruby
FILE_SERVER_PATH = '//examplefs/qa/selenium-videos/'
@driver = Selenium::Webdriver.for :remote, url: 'selenium-grid.example.com', desired_capabilities: :chrome
@session_id = @driver.session_id
@video_file_path = "#{FILE_SERVER_PATH}#{@driver.session_id}.mp4"
```

From there it could be sent to any reporting aggregator of your choice for easy linking of video to test results, and managed (such as being removed in the event of a passing test or renamed to something more useful) entirely from the client side.
