### ISSUE TITLE
[🚀 Feature]: Subpath parameter for subpath ingress configurations

### ISSUE THREAD

**Issue by med502** [SeleniumHQ/selenium#10847]
### Feature and motivation

Adding parameter for subpath configuration so inside container application can work on different path than root.

I've tested rewrite rules on ingress and they do not work correctly.

### Usage example

Currently application works on http://localhost:4444 inside of the container, unfortunately in ingress implementation with reverse-proxy application will not respond correctly to ingress configuration where path is configured different than "/"
New parameter would allow to change base URL of the application to work on http://localhost/selenium:4444 which will allow correct communication with ingress.

**Comment by diemol** [comment]
Which app do you mean? The Grid UI?

**Comment by med502** [comment]
> Which app do you mean? The Grid UI?

This is regarding hub component.
I am implementing cluster of hub with few worker nodes for our tester chapter.

**Comment by diemol** [comment]
Still a bit lost. Can you describe where you use the URL for the app you mentioned?

**Comment by med502** [comment]
![image](https://user-images.githubusercontent.com/102814247/177299829-42c1afa7-7a81-4bc2-9020-b6b1fe854683.png)

Using diagram above
HUB component is accessible over kubernetes ingress wtih nginx class.
Whenever I use subpath in ingress configuration so application will be on mydomain.com/selenium application is not accessible
I can only use root path so I can set selenium to work only on mydomain.com

In that case various application require additional parameter to work on subpath which is different than root path of the URL
example for grafana https://grafana.com/tutorials/run-grafana-behind-a-proxy/

**Comment by diemol** [comment]
I am still not understanding. Do you mean the user interface of the Grid, where you can see the running sessions and node stereotypes? Or do you mean the URL endpoint where you start sessions? Both live inside the Hub.

**Comment by med502** [comment]
Both interface and checking status with command below

```curl -X GET https://mydomain.com/selenium/status```

**Comment by diemol** [comment]
I see. It should actually work. Can you share the work you have done so we can try it as well? Maybe in a GitHub repository with instructions.

**Comment by med502** [comment]
I've deployed selenium from helm chart from this link
```https://github.com/pedrodotmc/docker-selenium/tree/selenium-grid-helm-chart/chart/selenium-grid```
and then I've updated ingress to look like this
```
apiVersion: v1
items:
- apiVersion: extensions/v1beta1
  kind: Ingress
  metadata:
    annotations:
      kubernetes.io/publicEndpoints: ;[{"address":[""]."port":443,"protocol":"HTTPS","serviceName":"selenium:selenium-hub","ingressName":"selenium:selenium-ingress","hostname":"mydomain.com"."path":"/selenium","allNodes":false}]'
      kubernetes.io/ingress.classs: nginx
      nginx.ingress.kubernetes.io/add-base-url: "true"
      meta.helm.sh/release-name: selenium-grid
      meta.helm.sh/release-namespace: selenium
    name: slenium-ingress
    namespace: selenium  
  spec:
    rules:
    -   host: mydomain.com
        http:
          paths:
          - backend:
              serviceName: selenium-hub
              servicePort: 4444
            path: /selenium
            pathType: Prefix
    tls:
    - host:
      - mydomain.com
      secretName: mydomain-secret     
```

Problem occurs as our nginx ingress is behind AWS load balancer and reverse proxy.
I've tried to add rewrite /$2 annotation but that deos not work as well
