### ISSUE TITLE
[🐛 Bug]: Sessions page is white (TypeError: e is undefined) when browserName is custom value

### ISSUE THREAD

**Issue by mythsunwind** [SeleniumHQ/selenium#10907]
### What happened?

If a custom value for browserName is used the sessions overview of the grid causes a javascript error and shows a white page.

(We use a custom value for the browserName to specify a specific phone on app tests)

### How can we reproduce the issue?

relay.toml
```toml
[server]
port = 5555

[node]
detect-drivers = false

[relay]
url = "http://localhost:4723"
status-endpoint = "/status"
configs = [
  "1", "{\"browserName\": \"Google-sargo-Pixel 3a-9BMAY1KFA3\", \"platformName\": \"android\", \"version\": \"11\"}"
]
```

Steps:
1. Install uiautomator2 driver: `appium driver install uiautomator2`
2. Start appium on port 4723: `ANDROID_HOME=/path/to/android-sdk/ appium`
3. Start android emulator to have at least one device: `emulator -avd android10`
4. Wait a bit for the server to come up
5. Run hub: `java -jar selenium-server-4.3.0.jar hub`
6. Run node: `java -jar selenium-server-4.3.0.jar node --config relay.toml`
7. Create session with curl: `curl -H "Content-Type:application/json; charset=utf-8" -X POST http://127.0.0.1:4444/wd/hub/session -d '{"capabilities":{"alwaysMatch":{"platformName":"android","appium:automationName":"uiautomator2"}}}'`
8. Open http://localhost:4444/ui#/sessions in a browser quickly
9. Reload until the session is shown

### Relevant log output

```shell
TypeError: e is undefined
    xf browser-logo.tsx:12
    Sf BrowserLogo.tsx:29
    React 7
    k scheduler.production.min.js:13
    R scheduler.production.min.js:14
    8886 scheduler.production.min.js:14
    Webpack 12
```

### Operating System

macOS

### Selenium version

4.3.0, 4.4.0, 4.5.0

### What are the browser(s) and version(s) where you see this issue?

Firefox, Chrome

### What are the browser driver(s) and version(s) where you see this issue?

uiautomator2

### Are you using Selenium Grid?

4.3.0, 4.4.0, 4.5.0
