### ISSUE TITLE
[🚀 Feature]: use yaml dsl to drive selenium test, simplify test development

### ISSUE THREAD

**Issue by shigebeyond** [SeleniumHQ/selenium#10980]
### Feature and motivation

I write [SeleniumBoot](https://github.com/shigebeyond/SeleniumBoot) to use yaml in test development, It's very simple to use Selenium

### Usage example

1. download image flow
[demo video](https://www.zhihu.com/zvideo/1542455008884322304)
[demo code](https://github.com/shigebeyond/SeleniumBoot/blob/main/example/step-netbian.yml)
```yaml
- # home page
  goto:
    url: https://pic.netbian.com/4kmeinv/index.html
  # download images
  download_img_elements_by:
    xpath: '//ul[@class="clearfix"]/li/a/img'
    #save_dir: downloads # default save dir is downloads
```

2. complex flow
[demo video](https://www.zhihu.com/zvideo/1542453686449471488)
[demo code](https://github.com/shigebeyond/SeleniumBoot/blob/main/example/step-jym.yml)
```yaml
- # login page
  goto:
    url: http://admin.jym1.com/login
  sleep: 2
  # input and submit login form
  submit_form:
    account: '18877310999'
    passwd: '123456'
- # goods list page
  goto:
    url: http://admin.jym1.com/goods/goods_service_list
    # extract variable from html
    extract_by_xpath:
      goods_id: //table/tbody/tr[1]/td[1] # first row and first column
  #  extract_by_css:
  #    goods_id: table>tbody>tr:nth-child(1)>td:nth-child(1)
- # goods detail page
  goto:
    url: http://admin.jym1.com/goods/goods_info?id=$goods_id&type=1
- # create store page
  goto:
    url: http://admin.jym1.com/store/add_store
  upload: # upload image
    url: http://admin.jym1.com/upload/common_upload_img/store_img
    files: # upload field and file
      file: /home/shi/fruit.jpeg
    extract_by_jsonpath: # extract variable from json response
      img: $.data.url
  # post data to create store
  post:
    url: http://admin.jym1.com/store/add_store
    is_ajax: true
    data: # post data
      # field : value
      store_name: teststore-${random_str(6)}
      store_logo_url: '$img'
      store_img_urls: '["$img"]'
      province: 450000
      city: 450100
      district: 450102
      address: testadd
      phone: 1347115${random_int(4)}
      business_day_from: 1
      business_day_to: 1
      work_start_time: 09:00:00 - 20:00:00
      store_type: 0
      licence_url: '$img'
      license_code: 91450100788439413D
      card_true_name: shi
      bank_name: 中国工商银行
      bank_card_num: 6222024100018669328
      store_work_time: '["{\"date_from\":\"1\",\"date_to\":\"1\",\"work_start_time\":\"09:00:00\",\"work_end_time\":\"20:00:00\"}"]'
- # store list page, to check the created store
  goto:
    url: http://admin.jym1.com/store/store_list
  sleep: 2
```
