### ISSUE TITLE
[🚀 Feature]: Allow user to provide a different base URL for the grid UI

### ISSUE THREAD

**Issue by StellarNear** [SeleniumHQ/selenium#11647]
### Feature and motivation

For the moment the base URL of a grid is locked to be /ui/ at root level.
For my usage i had to manually change the path in the file : selenium/grid-ui/package.json at line 38 `"homepage": "/ui"` to `"homepage": "/selenium/ui"`

Because for my usage the base URL host multiple services (so i have my URL like this www.myUrl.com/selenium/ui) 

Currently i found no other way to provide the grid a custom base without having to recompile everything after a manual change.

### Usage example

The grid could simply read an environment variable such as GRID_BASE_URL and if this variable exist use it instead of the /ui written in the code

**Comment by krmahadevan** [comment]
@StellarNear i remember adding this capability as part of https://github.com/SeleniumHQ/selenium/pull/11271

Can you please check this once again on `4.8.0`?

**Comment by StellarNear** [comment]
@krmahadevan Oh i didn't catched this new feature (i was using an older version of the grid) So i will have to add --sub-path as a launching argument for the router jar part and it will do all the configuration even for the JS redirect of everything in the UI of the grid from the front end ?

**Comment by krmahadevan** [comment]
@StellarNear yes. Can you please try and post back if you noticed any gaps? All selenium grid internal Urls should work with the prefix now.

**Comment by StellarNear** [comment]
Ok i did test with the sub-path option and the UI of the grid is still hardcoded.
For i used `--sub-path /selenium` example i got some 404 because the js and other files are searched into path /ui/static and not /selenium/ui/static
`<!doctype html><html lang="en"><head><meta charset="utf-8"/><link href="/ui/favicon.svg" rel="icon" type="image/svg"><meta content="width=device-width,initial-scale=1" name="viewport"/><link href="/ui/logo192.png" rel="apple-touch-icon"/><link href="/ui/manifest.json" rel="manifest"/><title>Selenium Grid</title><script defer="defer" src="/ui/static/js/main.415a1a1c.js"></script><link href="/ui/static/css/main.ce2bf04a.css" rel="stylesheet"></head><body><noscript>You need to enable JavaScript to run this app.</noscript><div id="root"></div></body></html>`

You can see the code of the page still has href etc pointing to /ui without any concern of my rebasing. So for now i will still have to recompile everything which is sad because i want to be able to use directly your image. 

As a final tough i think your feature is a big nice start to what i need but a little step will be needed to allow the UI to use the subpath also.

**Comment by diemol** [comment]
@StellarNear Can you share the details showing how you tried it? I tested the feature and it was working both the UI and the commands.

**Comment by StellarNear** [comment]
i did a kubernetes deployment like this one : 
```
apiVersion: v1
kind: Service
metadata:
  name: selenium-hub
  namespace: default
  labels:
    app.kubernetes.io/name: selenium
    app.kubernetes.io/component: hub
spec:
  selector:
    app.kubernetes.io/name: selenium
    app.kubernetes.io/component: hub
  ports:
    - name: web
      protocol: TCP
      port: 4444
      targetPort: 4444
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: selenium-hub
  namespace: default
  labels:
    app.kubernetes.io/name: selenium
    app.kubernetes.io/component: hub
spec:
  replicas: 1
  selector:
    matchLabels:
      app.kubernetes.io/name: selenium
      app.kubernetes.io/component: hub
  template:
    metadata:
      labels:
        app.kubernetes.io/name: selenium
        app.kubernetes.io/component: hub
    spec:
      containers:
        - name: selenium-hub
          image: selenium/hub:4.8.0-20230210
          imagePullPolicy: "IfNotPresent"
          env:
            - name: SE_BIND_HOST
              value: "false"
            - name: SE_SESSION_REQUEST_TIMEOUT
              value: "600"
            - name: SE_SESSIONQUEUE_REQUEST_TIMEOUT
              value: "600"
            - name: SE_SESSION_RETRY_INTERVAL
              value: "5"
            - name: SE_OPTS
              value: "--registration-secret 42 --sub-path /selenium"
          ports:
            - containerPort: 4444
              protocol: TCP
          resources:
            limits:
              cpu: "0.5"
              memory: 384Mi
            requests:
              cpu: "0.25"
              memory: 256Mi
```

The pod starts nicely and run like it supposed to i guess since the log show that is up and running like you can see in this log : 
```
15:24:32.034 INFO [BoundZmqEventBus.<init>] - XPUB binding to [binding to tcp://*:4442, advertising as tcp://**.***.*.**:4442], XSUB binding to [binding to tcp://*:4443, advertising as tcp://**.***.*.**:4443]
15:24:32.327 INFO [UnboundZmqEventBus.<init>] - Connecting to tcp://**.***.*.**:4442 and tcp://**.***.*.**:4443
15:24:32.417 INFO [UnboundZmqEventBus.<init>] - Sockets created
15:24:33.419 INFO [UnboundZmqEventBus.<init>] - Event bus ready
15:24:36.613 INFO [Hub.execute] - Started Selenium Hub 4.8.0 (revision 267030adea): http://**.***.*.**:4444
```
