### ISSUE TITLE
[🐛 Bug]: Get download file in client

### ISSUE THREAD

**Issue by yairddj2** [SeleniumHQ/selenium#12034]
### What happened?

i have dynamic grid env , was working with old implantation for support download ( - `SE_OPTS=--downloads-path /home/seluser/Downloads` ,etc)  and it worked fine . 
now started to config new download way   ( - `SE_OPTS=--enable-managed-downloads true`)

https://www.selenium.dev/documentation/grid/configuration/cli_options/#enabling-managed-downloads-by-the-node. 

issue is after download file in browser during test,  and run get for `http://localhost:4444/session/my session id/se/files` got an empty respond value like below .

```json
{
  "value": {
    "names": [
    ]
  }
}
```

### How can we reproduce the issue?

```shell
in node docker set environment : - SE_OPTS=--enable-managed-downloads true
in code set desired_capabilities=  "se:downloadsEnabled": "true"
```

### Relevant log output

```shell
no error in log
```

### Operating System

dynamic-grid docker

### Selenium version

latest

### What are the browser(s) and version(s) where you see this issue?

latest

### What are the browser driver(s) and version(s) where you see this issue?

latest

**Comment by titusfortner** [comment]
Are you calling this before you quit your session?

**Comment by yairddj2** [comment]
yes , only while session is active I get respond , if test/session is end then error is deferent (something like no session found )

**Comment by titusfortner** [comment]
Is it possible the file has not finished downloading?

**Comment by yairddj2** [comment]
No this is not the case file is download and only then i tried to get file info , did develop team test "enable-managed-downloads true" in dynamic grid , if yes can you share the setup ?
maybe something is missing in mine.

**Comment by diemol** [comment]
We missed Dynamic Grid when we revamped the downloads feature. I just fixed it so it works out of the box in 4.10.0.

In the mean time, you can add manually the `"se:downloadsEnabled": "true"` capability to the stereotypes in the `config.toml`.

**Comment by diemol** [comment]
```
    "selenium/standalone-firefox:4.9.1-20230508", '{"browserName": "firefox", "platformName": "linux", "se:downloadsEnabled": true}',
    "selenium/standalone-chrome:4.9.1-20230508", '{"browserName": "chrome", "platformName": "linux", "se:downloadsEnabled": true}',
    "selenium/standalone-edge:4.9.1-20230508", '{"browserName": "MicrosoftEdge", "platformName": "linux", "se:downloadsEnabled": true}'
```

**Comment by yairddj2** [comment]
@diemol even after set as you suggested got the same issue of 200 respond code without values

**Comment by diemol** [comment]
This is what I used:

```toml
[docker]
# Configs have a mapping between the Docker image to use and the capabilities that need to be matched to
# start a container with the given image.
configs = [
    "selenium/standalone-firefox:4.9.1-20230508", '{"browserName": "firefox", "platformName": "linux", "se:downloadsEnabled": true}',
    "selenium/standalone-chrome:4.9.1-20230508", '{"browserName": "chrome", "platformName": "linux", "se:downloadsEnabled": true}',
    "selenium/standalone-edge:4.9.1-20230508", '{"browserName": "MicrosoftEdge", "platformName": "linux", "se:downloadsEnabled": true}'
    ]

# URL for connecting to the docker daemon
# host.docker.internal works for macOS and Windows.
# Linux could use --net=host in the `docker run` instruction or 172.17.0.1 in the URI below.
# To have Docker listening through tcp on macOS, install socat and run the following command
# socat -4 TCP-LISTEN:2375,fork UNIX-CONNECT:/var/run/docker.sock
url = "http://127.0.0.1:2375"
# Docker image used for video recording
video-image = "selenium/video:ffmpeg-4.3.1-20230508"

# Uncomment the following section if you are running the node on a separate VM
# Fill out the placeholders with appropriate values
#[server]
#host = <ip-from-node-machine>
#port = <port-from-node-machine>
```

docker compose

```yml
# To execute this docker-compose yml file use `docker-compose -f docker-compose-v3-dynamic-grid.yml up`
# Add the `-d` flag at the end for detached execution
# To stop the execution, hit Ctrl+C, and then `docker-compose -f docker-compose-v3-dynamic-grid.yml down`
version: "3"
services:
  node-docker:
    image: selenium/node-docker:4.9.1-20230508
    volumes:
      - ./assets:/opt/selenium/assets
      - ./NodeDocker/config.toml:/opt/bin/config.toml
      - /var/run/docker.sock:/var/run/docker.sock
    depends_on:
      - selenium-hub
    environment:
      - SE_EVENT_BUS_HOST=selenium-hub
      - SE_EVENT_BUS_PUBLISH_PORT=4442
      - SE_EVENT_BUS_SUBSCRIBE_PORT=4443
      - SE_OPTS=--enable-managed-downloads true

  selenium-hub:
    image: selenium/hub:4.9.1-20230508
    container_name: selenium-hub
    ports:
      - "4442:4442"
      - "4443:4443"
      - "4444:4444"
```

Test

```java
	void canListDownloadedFiles() throws InterruptedException, MalformedURLException {
		URL gridUrl = new URL(remoteUrl);
		ChromeOptions options = new ChromeOptions();
		options.setCapability("se:downloadsEnabled", true);
		RemoteWebDriver driver = new RemoteWebDriver(gridUrl, options);
		driver.get("https://www.selenium.dev/selenium/web/downloads/download.html");
		driver.findElement(By.id("file-1")).click();
		driver.findElement(By.id("file-2")).click();
		SessionId sessionId = driver.getSessionId();

		// Waiting for the file to be remotely downloaded
		TimeUnit.SECONDS.sleep(3);

		HttpRequest request = new HttpRequest(GET, String.format("/session/%s/se/files", sessionId));
		try (HttpClient client = HttpClient.Factory.createDefault().createClient(gridUrl)) {
			HttpResponse response = client.execute(request);
			Map<String, Object> jsonResponse = new Json().toType(string(response), Json.MAP_TYPE);
			@SuppressWarnings("unchecked")
			Map<String, Object> value = (Map<String, Object>) jsonResponse.get("value");
			@SuppressWarnings("unchecked")
			List<String> names = (List<String>) value.get("names");
			assertTrue(names.contains("file_1.txt"));
			assertTrue(names.contains("file_2.jpg"));
		} finally {
			driver.quit();
		}
	}
```

**Comment by yairddj2** [comment]
@diemol 
1)When 4.10.0 planed to be published ?
2)I set the same config as you shared but still empty respond when curl get to files list , the deferent between us is that I download the file via the vnc (manual on the browser and not via code) , also the get request for files list is like below and not via code as you did 
curl -X GET "http://localhost:4444/session/90c0149a-2e75-424d-857a-e78734943d4c/se/files"
is that makes any deferent ?

**Comment by diemol** [comment]
1. End of May.
2. The download needs to be done through the session, whatever you do manually is separate, Selenium cannot notice any manual interactions.

**Comment by titusfortner** [comment]
Isn't the driver setting the download location for the browser in general? Shouldn't that be the same whether the download was initiated by Selenium or manual on that browser? Pretty sure as long as the browser was started by selenium, any download should populate that directory, and downloaded files should be available via the endpoint...

**Comment by diemol** [comment]
Good point

**Comment by titusfortner** [comment]
but the session ID obviously has to match the browser that was used to download, and the endpoint does nothing to ensure files have "finished downloading."

**Comment by yairddj2** [comment]
Even after download the file from the test code files list is empty , file download location in endpoint is "/home/seluser/Downloads" is that ok?
Can you guys think on other config that missing ?

**Comment by diemol** [comment]
Seems you are opening the browser manually, is that right?

**Comment by yairddj2** [comment]
no , all by the code .


from selenium import webdriver
from selenium.webdriver.common.by import By
from selenium.webdriver.common.keys import Keys
from time import sleep

driver = webdriver.Remote(
   command_executor="http://xxxxx:4444/wd/hub",
   desired_capabilities={            
            "browserName": "chrome",                      
            "platformName": "linux",	
            "se:recordVideo": "True",
            "se:downloadsEnabled": "True"        
        })

driver.get("https://www.selenium.dev/selenium/web/downloads/download.html")

element = driver.find_element(By.ID, 'file-1')
element.click()
session = driver.session_id 
print (session)

sleep(300)

driver.quit()

**Comment by titusfortner** [comment]
Selenium generates a unique directory for downloads for each session, so the easiest way to access the files is with the endpoint

**Comment by yairddj2** [comment]
maybe this is the issue , files are download to "/home/seluser/Downloads"  and not to unique Selenium  directory ?

**Comment by titusfortner** [comment]
You need to enable downloads  when you start the grid, and you need to enable it in the capabilities when you start the browser. It should all be in the docs you linked at the top.

**Comment by theswordsmahin** [comment]
> maybe this is the issue , files are download to "/home/seluser/Downloads" and not to unique Selenium directory ?

@titusfortner @diemol 
Could we get clarification if this could be an issue and if it could be solved with some additional configuration? I am running into the same issue as @yairddj2 on Selenium Grid 4.10.0 and 4.9.1. From the VNC session, I can see files are finished downloading and I can open a shell and see files in `/home/seluser/Downloads` 

but `http://localhost:4444/session/<session-id>/se/files` always reports 
```
{
  "value": {
    "names": [
    ]
  }
}
```
Whether accessing from a web browser, or programmatically as in the examples. 

I've attempted using containers, selenium/node-firefox:4.10.0, selenium/node-chrome:4.10.0, and selenium/node-docker:4.10.0 (using the toml file provided by @diemol in an earlier comment), always making sure to specify `- SE_OPTS=--enable-managed-downloads true`

RemoteWebDriver is correctly requesting the download capability `options.setCapability("se:downloadsEnabled", true);` and verified the session capability from the Grid Hub. 

@titusfortner 
>Selenium generates a unique directory for downloads for each session, so the easiest way to access the files is with the endpoint

This comment is the only bit of information that I cant really find any evidence of, and what would make sense if I'm seeing downloads in `/home/seluser/Downloads` 

Thank you in advance

**Comment by titusfortner** [comment]
Is it working in chrome but not Firefox? The code is supposed to edit the options to set the unique download directory when the session starts. Can you turn on logging in the client code to see what is sent to/from the grid?

https://www.selenium.dev/documentation/webdriver/troubleshooting/logging/

**Comment by theswordsmahin** [comment]
Thanks for the quick reply!

It's not working in either browser browser for me, using the specific node images, nor the dynamic node image with the standalone images (as specified in the toml file). 

I will collect the requested logs on Monday, thanks for the link to docs on how to do that 👍

**Comment by theswordsmahin** [comment]
I have run the test again and collected the logs [selenium-logs.xml.txt](https://github.com/SeleniumHQ/selenium/files/12008460/selenium-logs.xml.txt) (if there are more classes to enable logging for that would be helpful please let me know)

And here is my test code:

```java
import static org.openqa.selenium.remote.http.Contents.string;

import java.net.MalformedURLException;
import java.net.URL;
import java.util.List;
import java.util.Map;
import java.util.concurrent.TimeUnit;
import java.util.logging.ConsoleHandler;
import java.util.logging.FileHandler;
import java.util.logging.Handler;
import java.util.logging.Level;
import java.util.logging.Logger;

import org.openqa.selenium.By;
import org.openqa.selenium.WebDriver;
import org.openqa.selenium.json.Json;
import org.openqa.selenium.manager.SeleniumManager;
import org.openqa.selenium.remote.DesiredCapabilities;
import org.openqa.selenium.remote.RemoteWebDriver;
import org.openqa.selenium.remote.SessionId;
import org.openqa.selenium.remote.http.HttpClient;
import org.openqa.selenium.remote.http.HttpMethod;
import org.openqa.selenium.remote.http.HttpRequest;
import org.openqa.selenium.remote.http.HttpResponse;
import org.testng.Assert;
import org.testng.annotations.AfterTest;
import org.testng.annotations.BeforeTest;
import org.testng.annotations.Test;

public class SeleniumTesting {
    private RemoteWebDriver driver;

    @BeforeTest
    public void setup() throws MalformedURLException {

        ConsoleHandler consoleHandler = new ConsoleHandler();
        consoleHandler.setLevel(Level.ALL);
        Handler fileHandler;
        try {
            fileHandler = new FileHandler("/qa-repo/automation/selenium-logs.xml");
            fileHandler.setLevel(Level.ALL);
            String[] classes = new String[] {
                    "",
                    WebDriver.class.getName(),
                    RemoteWebDriver.class.getName(),
                    SeleniumManager.class.getName()
            };
            for (String clazz : classes) {
                Logger seleniumLogger = Logger.getLogger(clazz);
                seleniumLogger.setLevel(Level.ALL);
                seleniumLogger.setUseParentHandlers(false);
                seleniumLogger.addHandler(fileHandler);
                seleniumLogger.addHandler(consoleHandler);
            }
        } catch (Exception e) {
            e.printStackTrace();
        }

        String hubUrl = "http://selenium-hub:4444/wd/hub";
        DesiredCapabilities capabilities = new DesiredCapabilities();
        capabilities.setBrowserName("chrome");
        capabilities.setCapability("se:downloadsEnabled", true);
        driver = new RemoteWebDriver(new URL(hubUrl), capabilities);
        driver.manage().window().maximize();
    }

    @Test
    public void testing() throws InterruptedException, MalformedURLException {
        driver.get("https://www.selenium.dev/selenium/web/downloads/download.html");
        driver.findElement(By.id("file-1")).click();
        driver.findElement(By.id("file-2")).click();
        SessionId sessionId = driver.getSessionId();
        System.out.println(sessionId);
        // // Waiting for the file to be remotely downloaded
        TimeUnit.SECONDS.sleep(3);

        HttpRequest request = new HttpRequest(HttpMethod.GET, String.format("/session/%s/se/files", sessionId));
        try (HttpClient client = HttpClient.Factory.createDefault()
                .createClient(new URL("http://selenium-hub:4444/"))) {
            HttpResponse response = client.execute(request);
            Map<String, Object> jsonResponse = new Json().toType(string(response), Json.MAP_TYPE);
            @SuppressWarnings("unchecked")
            Map<String, Object> value = (Map<String, Object>) jsonResponse.get("value");
            @SuppressWarnings("unchecked")
            List<String> names = (List<String>) value.get("names");
            System.out.println(names);
            Assert.assertEquals(names.size(), 2, "Found 2 files downloaded");
        } finally {
            driver.quit();
        }

    }

    @AfterTest
    public void quit() {
        driver.quit();
    }
}
```

And my relevant docker compose services
```yaml
  chrome:
    image: selenium/node-chrome:4.10.0
    depends_on:
      - selenium-hub
    environment:
      - SE_EVENT_BUS_HOST=selenium-hub
      - SE_EVENT_BUS_PUBLISH_PORT=4442
      - SE_EVENT_BUS_SUBSCRIBE_PORT=4443
      - SE_NODE_MAX_SESSIONS=10
      - SE_NODE_OVERRIDE_MAX_SESSIONS=true
      - SE_SCREEN_WIDTH=1400
      - SE_SCREEN_HEIGHT=900
      - SE_OPTS=--enable-managed-downloads true
    ports:
      - "7901:7900"

  firefox:
    image: selenium/node-firefox:4.10.0
    shm_size: 2gb
    depends_on:
      - selenium-hub
    environment:
      - SE_EVENT_BUS_HOST=selenium-hub
      - SE_EVENT_BUS_PUBLISH_PORT=4442
      - SE_EVENT_BUS_SUBSCRIBE_PORT=4443
      - SE_NODE_MAX_SESSIONS=10
      - SE_NODE_OVERRIDE_MAX_SESSIONS=true
      - SE_SCREEN_WIDTH=1400
      - SE_SCREEN_HEIGHT=900
      - SE_OPTS=--enable-managed-downloads true
    ports:
      - "7902:7900"

  selenium-hub:
    image: selenium/hub:4.10.0
    ports:
      - "4442:4442"
      - "4443:4443"
      - "4444:4444"
```

I have also verified that files are finished downloading by setting a breakpoint on the assertion, and navigating to the selenium-hub url manually to look the response, it always returns
```json
{
  "value": {
    "names": [
    ]
  }
}
```

Thank you again for taking the time to investigate this

**Comment by titusfortner** [comment]
How is `SE_OPTS` parsed? I don't see it in our docs...
At this point I need help from @krmahadevan / @diemol :)
The options look like they are sending correctly.

**Comment by diemol** [comment]
I need to see the grid logs, I checked the attached file and I don't see how the grid starts.

**Comment by theswordsmahin** [comment]
Added `--log-level FINEST` to the SE_OPTS for the hub and node, reran the test

[chrome-logs.txt](https://github.com/SeleniumHQ/selenium/files/12008874/chrome-logs.txt)
[grid-logs.txt](https://github.com/SeleniumHQ/selenium/files/12008875/grid-logs.txt)

**Comment by theswordsmahin** [comment]
@diemol Just making sure that the logs provided are what you were looking for, or if you needed something else from me to help debug this issue. Thanks in advance

**Comment by theswordsmahin** [comment]
Hi there @titusfortner @diemol 
Just checking in to see if there was any more information I could collect to help debug this issue, or if you had any status to report. Thank you!

**Comment by jonathan-fortin** [comment]
Hi,

Any news on this bug?

 It was postponed in several versions. Will it be fixed in 3.14?

Thanks!

**Comment by jonathan-fortin** [comment]
Hi,

Any news on this bug?


Thanks!

**Comment by titusfortner** [comment]
What is the status of this issue? Do we know what we need to do to address it?

**Comment by giuliohome** [comment]
This is working in docker standalone, we're going to try in selenium grid too asap.

BTW Notice that the selenium managed download are zipped:
https://stackoverflow.com/questions/77370931/how-are-selenium-managed-downloads-encrypted

**Comment by krmahadevan** [comment]
@giuliohome - You should see a full fledged sample that demonstrates how to work with this in [our documentation](https://www.selenium.dev/documentation/grid/configuration/cli_options/#enabling-managed-downloads-by-the-node)

Note:

The sample is most likely going to be needing an update once a newer version of selenium (that includes the Java client) gets released.

**Comment by giuliohome** [comment]
@krmahadevan Thanks, I missed this sentence [here](https://www.selenium.dev/documentation/grid/configuration/cli_options/#dowloading-a-file);

> The file contents are Base64 encoded and **they need to be unzipped**.

Regarding the grid we are using [this helm chart](https://github.com/SeleniumHQ/docker-selenium/blob/trunk/charts/selenium-grid), so my understanding is that we have to set 


```yaml
  extraEnvironmentVariables:
    - name: "SE_OPTS"
      value: "--enable-managed-downloads true"
```

under chromeNode and firefoxNode and edgeNode

Is it confirmed?

**Comment by giuliohome** [comment]
Nope!
We are getting this error from the log
`Was passed main parameter '--enable-managed-downloads' but no main parameter was defined in your arg class`
with the above values in the helm chart
Very strange IMHO because we set
```
  extraEnvironmentVariables:
    - name: "SE_OPTS"
      value: "--enable-managed-downloads true"
```

**Comment by giuliohome** [comment]
Tested (on a DOKS cluster) and it works!

```
helm list
NAME            NAMESPACE       REVISION        UPDATED                                 STATUS          CHART                    APP VERSION    
selenium-grid   default         1               2023-10-27 19:25:47.201083976 +0000 UTC deployed        selenium-grid-0.23.0     4.14.1-20231025
```


```
const post1 = await fetch(`${selenium_url}/wd/hub/session/${sessionId}/se/files`, {
...   method: "POST",
...   body: JSON.stringify({
...     'name': jsonResponse1.value.names[0]
...   }),
...   headers: {
...     "Content-type": "application/json; charset=utf-8"
...   }
... });
undefined
> const jsonPost = await post1.json();
undefined
> jsonPost
{
  value: {
    filename: 'BrowserStack - List of devices to test on.csv',
    contents: 'UEsDBBQACAgIAEacW1cAAAAAAAAAAAAAAAAtAAAAQnJvd3NlclN0YWNrIC0gTGlzdCBvZiBkZXZpY2VzIHRvIHRlc3Qgb24uY3N27VZRc5pAEH53xv+wPwAbwJjEvNE0Y2xjwojt2McTVtkp3tG7Q6W/vgeiTQST2OlDHzLDwN3tx97efh+7BCKTIV5DrHWqrs/OZlKsFUqlWfjjQyiWZxqV7gje0TF2JC1i3VmKGSXYiXBFISrLstqt8nZPSoOYQ2WAuZBg/EjdydIt7KtC0DEpSAroOkYOucggZiuELNUCnJ5t25Bx+pkhrEiRFlIBg6XgOi5dfCqdA2dLtKrxJE/RegzMBSsTOQnebpEfC47gdK1RGa1FBuD0/hhc8KWAEds8A5y3WwFbqowvYMAStskhcJ0dwuORFBRZjlNDeb06yq6jHPsQ1W+3psTEkmCMkbk/CI1w1YAin0VwZZIwYbME9T7cl9O/MGySCWCWKeKoFL7Owwz1Gs3ClgrGI+ja9jsrp7FyuIXrqKZIdsd2Do9bGabjw0QdODbbgnfZ5HogxCJB8GmDCVzUEO5rykGuUaaS3iKZpZCFkfFjUkGjgPxdLv+LXKrdT5NLtccV+EmmjgQQ3IJru+4rUXiO23S6egr7b6GjW3fmVJm+fKlcelFE2siMJXvdqxRDmlMIphMNUCwkS+O8oY3diIxrme+k6+wGrrENeUTM2h6iv3t6xUsxcWZ9o5WA786l9ZimwijOGD6zlHErEDyHaYqSGDg2DIcNK+3WR8l+UWLVJalqa7Zj8CPcUCisu4ytkeBOcHOW/tQkzHyWImFQDGDg2gYaiEzH4M0lhWz3gt+14Z407ufn1bzdeqBFEZk15HPitIFgaTIEvf38Tugiaj9huUGPM6UMuPbB2dYz1vs3f8VOvcuVfeuwhB2nrRp0j9JX1+ZlUXqOsvokfyXszRwPD3MUFJo/jfYauyfo4PnK7UVJ4IniqFUzuDENokEyI288eSqZx8leMhMMuYDA98Zf4PwU/TQU4i0FpQSCf/C3+xtQSwcIezRMLMMCAAAyCwAAUEsBAhQAFAAICAgARpxbV3s0TCzDAgAAMgsAAC0AAAAAAAAAAAAAAAAAAAAAAEJyb3dzZXJTdGFjayAtIExpc3Qgb2YgZGV2aWNlcyB0byB0ZXN0IG9uLmNzdlBLBQYAAAAAAQABAFsAAAAeAwAAAAA='
  }
}
> content = new Buffer.from(jsonPost.value.contents, 'base64');
<Buffer 50 4b 03 04 14 00 08 08 08 00 46 9c 5b 57 00 00 00 00 00 00 00 00 00 00 00 00 2d 00 00 00 42 72 6f 77 73 65 72 53 74 61 63 6b 20 2d 20 4c 69 73 74 20 ... 861 more bytes>
> fs.writeFileSync('./content.zip', content);

```

Thank you all.

So, why is this issue still open?

**Comment by sushmithasv** [comment]
Hi, http://localhost:4444/session/my session id/se/files  returns an empty value. Is this issue resolved?

{
  "value": {
    "names": [
    ]
  }
}

**Comment by krmahadevan** [comment]
@titusfortner @diemol - I think we can go ahead and close this issue

I have tried using selenium `4.15.0`, coupled with docker tag `4.15.0-20231102`

Just for the sake of completeness, here's the docker compose file

```yaml
# To execute this docker-compose yml file use `docker-compose -f docker-compose-v3.yml up`
# Add the `-d` flag at the end for detached execution
# To stop the execution, hit Ctrl+C, and then `docker-compose -f docker-compose-v3.yml down`
version: "3"
services:
  chrome:
    image: selenium/node-chrome:4.15.0-20231102
    shm_size: 2gb
    depends_on:
      - selenium-hub
    environment:
      - SE_EVENT_BUS_HOST=selenium-hub
      - SE_EVENT_BUS_PUBLISH_PORT=4442
      - SE_EVENT_BUS_SUBSCRIBE_PORT=4443
      - SE_OPTS=--enable-managed-downloads true

  firefox:
    image: selenium/node-firefox:4.15.0-20231102
    shm_size: 2gb
    depends_on:
      - selenium-hub
    environment:
      - SE_EVENT_BUS_HOST=selenium-hub
      - SE_EVENT_BUS_PUBLISH_PORT=4442
      - SE_EVENT_BUS_SUBSCRIBE_PORT=4443
      - SE_OPTS=--enable-managed-downloads true

  selenium-hub:
    image: selenium/hub:4.15.0-20231102
    container_name: selenium-hub
    ports:
      - "4442:4442"
      - "4443:4443"
      - "4444:4444"
```

<details>
<summary>TestNG test running on Chrome</summary>

```java
import org.openqa.selenium.By;
import org.openqa.selenium.chrome.ChromeOptions;
import org.openqa.selenium.json.Json;
import org.openqa.selenium.remote.RemoteWebDriver;
import org.openqa.selenium.remote.SessionId;
import org.openqa.selenium.remote.http.HttpClient;
import org.openqa.selenium.remote.http.HttpMethod;
import org.openqa.selenium.remote.http.HttpRequest;
import org.openqa.selenium.remote.http.HttpResponse;
import org.testng.Assert;
import org.testng.annotations.AfterTest;
import org.testng.annotations.BeforeTest;
import org.testng.annotations.Test;

import java.net.MalformedURLException;
import java.net.URL;
import java.util.List;
import java.util.Map;
import java.util.concurrent.TimeUnit;

import static org.openqa.selenium.remote.http.Contents.string;

public class SeleniumChromeTest {
    private RemoteWebDriver driver;

    @BeforeTest
    public void setup() throws MalformedURLException {
        String hubUrl = "http://localhost:4444";
        ChromeOptions options = new ChromeOptions();
        options.setEnableDownloads(true);
        driver = new RemoteWebDriver(new URL(hubUrl), options);
        driver.manage().window().maximize();
    }

    @Test
    public void testing() throws InterruptedException, MalformedURLException {
        driver.get("https://www.selenium.dev/selenium/web/downloads/download.html");
        driver.findElement(By.id("file-1")).click();
        driver.findElement(By.id("file-2")).click();
        SessionId sessionId = driver.getSessionId();
        System.out.println(sessionId);
        // // Waiting for the file to be remotely downloaded
        TimeUnit.SECONDS.sleep(3);

        HttpRequest request = new HttpRequest(HttpMethod.GET, String.format("/session/%s/se/files", sessionId));
        try (HttpClient client = HttpClient.Factory.createDefault()
                .createClient(new URL("http://localhost:4444/"))) {
            HttpResponse response = client.execute(request);
            Map<String, Object> jsonResponse = new Json().toType(string(response), Json.MAP_TYPE);
            @SuppressWarnings("unchecked")
            Map<String, Object> value = (Map<String, Object>) jsonResponse.get("value");
            @SuppressWarnings("unchecked")
            List<String> names = (List<String>) value.get("names");
            System.out.println(names);
            Assert.assertEquals(names.size(), 2, "Found 2 files downloaded");
        }
    }

    @AfterTest(alwaysRun = true)
    public void quit() {
        driver.quit();
    }
}
```

</details>


<details>
<summary>TestNG test running on Firefox</summary>

```java
import org.openqa.selenium.By;
import org.openqa.selenium.firefox.FirefoxOptions;
import org.openqa.selenium.json.Json;
import org.openqa.selenium.remote.RemoteWebDriver;
import org.openqa.selenium.remote.SessionId;
import org.openqa.selenium.remote.http.HttpClient;
import org.openqa.selenium.remote.http.HttpMethod;
import org.openqa.selenium.remote.http.HttpRequest;
import org.openqa.selenium.remote.http.HttpResponse;
import org.testng.Assert;
import org.testng.annotations.AfterTest;
import org.testng.annotations.BeforeTest;
import org.testng.annotations.Test;

import java.net.MalformedURLException;
import java.net.URL;
import java.util.List;
import java.util.Map;
import java.util.concurrent.TimeUnit;

import static org.openqa.selenium.remote.http.Contents.string;

public class SeleniumFirefoxTest {
    private RemoteWebDriver driver;

    @BeforeTest
    public void setup() throws MalformedURLException {
        String hubUrl = "http://localhost:4444";
        FirefoxOptions options = new FirefoxOptions();
        options.setEnableDownloads(true);
        driver = new RemoteWebDriver(new URL(hubUrl), options);
        driver.manage().window().maximize();
    }

    @Test
    public void testing() throws InterruptedException, MalformedURLException {
        driver.get("https://www.selenium.dev/selenium/web/downloads/download.html");
        driver.findElement(By.id("file-1")).click();
        driver.findElement(By.id("file-2")).click();
        SessionId sessionId = driver.getSessionId();
        System.out.println(sessionId);
        // // Waiting for the file to be remotely downloaded
        TimeUnit.SECONDS.sleep(3);

        HttpRequest request = new HttpRequest(HttpMethod.GET, String.format("/session/%s/se/files", sessionId));
        try (HttpClient client = HttpClient.Factory.createDefault()
                .createClient(new URL("http://localhost:4444/"))) {
            HttpResponse response = client.execute(request);
            Map<String, Object> jsonResponse = new Json().toType(string(response), Json.MAP_TYPE);
            @SuppressWarnings("unchecked")
            Map<String, Object> value = (Map<String, Object>) jsonResponse.get("value");
            @SuppressWarnings("unchecked")
            List<String> names = (List<String>) value.get("names");
            System.out.println(names);
            Assert.assertEquals(names.size(), 2, "Found 2 files downloaded");
        }
    }

    @AfterTest(alwaysRun = true)
    public void quit() {
        driver.quit();
    }
}
```

</details>
