### ISSUE TITLE
[🐛 Bug]: Selenium grid working for capability "appium:browserName": 'Chrome' and not "browserName": 'Chrome',

### ISSUE THREAD

**Issue by krishtoautomate** [SeleniumHQ/selenium#12640]
### What happened?

used below capabilities to run tests on device browser and tests are going to Queue

{

  "browserName": "Chrome",
  "platformName": "ANDROID",
  "appium:automationName": "UIAutomator2"
}

with below capabilities, tests are running on device browser without issue.

{
  "appium:browserName": "Chrome",
  "platformName": "ANDROID",
  "appium:automationName": "UIAutomator2"
}

attached relay details:

[ANDROID-06a49bf4.txt](https://github.com/SeleniumHQ/selenium/files/12476835/ANDROID-06a49bf4.txt)
[ANDROID-06a49bf4.yml.txt](https://github.com/SeleniumHQ/selenium/files/12476848/ANDROID-06a49bf4.yml.txt)
[ANDROID-06a49bf4.txt](https://github.com/SeleniumHQ/selenium/files/12476855/ANDROID-06a49bf4.txt)
[ANDROID-06a49bf4.yml.txt](https://github.com/SeleniumHQ/selenium/files/12476856/ANDROID-06a49bf4.yml.txt)

### How can we reproduce the issue?

```shell
attached relay details above.

relayed device as appium node to selenium grid.


use below capabilites to run tests to reproduce issue, tests are waiting in queue till timeout:

{

  "browserName": "Chrome",
  "platformName": "ANDROID",
  "appium:automationName": "UIAutomator2"
}
```

### Relevant log output

```shell
tests are waiting in queue till timeout when used below capabilities:

{

  "browserName": "Chrome",
  "platformName": "ANDROID",
  "appium:automationName": "UIAutomator2"
}
```

### Operating System

macOS Ventura

### Selenium version

Java JDK 11

### What are the browser(s) and version(s) where you see this issue?

Chrome

### What are the browser driver(s) and version(s) where you see this issue?

ChromeDriver 116

### Are you using Selenium Grid?

4.11

**Comment by diemol** [comment]
```toml
        [server]
        host = "172.21.34.232"
        url = "http://172.21.34.232:5552"
        port = 5552
        # session-request-timeout = 1800

        [events]
        publish = "tcp://172.21.34.239:4442"
        subscribe = "tcp://172.21.34.239:4443"

        [node]
        # url = 172.21.34.232
        detect-drivers = false
        max-sessions = 1
        session-timeout = 180

        [relay]
        url = "http://172.21.34.232:4782"
        service-host = "172.21.34.232"
        service-port = 4782
        status-endpoint = "/status"

        configs = [
            "1", "{\"platformName\": \"ANDROID\", \"appium:udid\": \"06a49bf4\", \"appium:deviceName\": \"06a49bf4\",\"appium:automationName\": \"UIAutomator2\", \"appium:systemPort\":8301, \"appium:platformVersion\": \"13\", \"appium:deviceClass\":\"NA\"}"
        ]
```

```toml
        [server]
        host = "172.21.34.232"
        url = "http://172.21.34.232:5552"
        port = 5552
        # session-request-timeout = 1800

        [events]
        publish = "tcp://172.21.34.239:4442"
        subscribe = "tcp://172.21.34.239:4443"

        [node]
        # url = 172.21.34.232
        detect-drivers = false
        max-sessions = 1
        session-timeout = 180

        [relay]
        url = "http://172.21.34.232:4782"
        service-host = "172.21.34.232"
        service-port = 4782
        status-endpoint = "/status"

        configs = [
            "1", "{\"platformName\": \"ANDROID\", \"appium:udid\": \"06a49bf4\", \"appium:deviceName\": \"06a49bf4\",\"appium:automationName\": \"UIAutomator2\", \"appium:systemPort\":8301, \"appium:platformVersion\": \"13\", \"appium:deviceClass\":\"NA\"}"
        ]
```
