### ISSUE TITLE
[🐛 Bug]: Net::ReadTimeout with #<TCPSocket:(closed)>

### ISSUE THREAD

**Issue by srghma** [SeleniumHQ/selenium#13404]
### What happened?

my capybara config

```rb
require 'capybara'
require 'selenium-webdriver'

raise %(empty ENV["APP_HOST"])            unless ENV["APP_HOST"]
raise %(empty ENV["HUB_URL"])             unless ENV["HUB_URL"]
raise %(empty ENV["REMOTE_DOWNLOAD_DIR"]) unless ENV["REMOTE_DOWNLOAD_DIR"]
raise %(empty ENV["CHROME_HEADLESS"])     unless ENV["CHROME_HEADLESS"] == "true" || ENV["CHROME_HEADLESS"] == "false"

Capybara.app_host = ENV["APP_HOST"]
Capybara.run_server = false

Capybara.register_driver :selenium_chrome do |app|
  # https://github.com/SeleniumHQ/selenium/wiki/Ruby-Bindings#internal-timeouts
  # change from 60 to 240 to prevent the "Net::ReadTimeout with #<TCPSocket:(closed)>"
  # client = Selenium::WebDriver::Remote::Http::Default.new
  # client.read_timeout = 240

  # doesnt work
  options = Selenium::WebDriver::Chrome::Options.new(
    logging_prefs: { # will go to @logging_prefs, not @options
      browser: 'ALL',
      driver: 'ALL'
    },
    args: [
      "verbose",
      "ignore-certificate-errors",
      "lang=en",
      "no-default-browser-check",
      "start-maximized",
      "disable-extensions",
      # 'window-size=1920,1080',
      "no-sandbox",
      # "disable-browser-side-navigation", # https://stackoverflow.com/questions/69173469/meaning-of-selenium-chromeoptions
      # "disable-dev-shm-usage",
      "log-path=/chromedriver.log",
      # "user-data-dir=/chromeuserdatadir",
      "log-level=INFO",
      "disable-gpu",
      ENV["CHROME_HEADLESS"] == "true" ? "headless" : nil,
      # "user-agent=Mozilla/5.0 (Windows NT 10.0; Win64; x64 AppleWebKit/537.36 (KHTML, like Gecko Chrome/91.0.4472.124 Safari/537.36",
    ].compact,
    prefs: {
      download: {
        default_directory:    ENV["REMOTE_DOWNLOAD_DIR"],
        prompt_for_download:  false,
        directory_upgrade:    true,
        extensions_to_open:   ""
      },
      plugins: {
        plugins_disabled: ["Chrome PDF Viewer"]
      }
    }
  )

  options = Selenium::WebDriver::Chrome::Options.new
  # options.args << '--headless'
  # options.args << '--disable-gpu'
  # Sandbox cannot be used inside unprivileged Docker container
  # options.args << '--no-sandbox'

  # options.add_argument("--ignore-certificate-errors")
  # options.add_argument("--lang=en")
  # options.add_argument("--no-default-browser-check")
  # options.add_argument("--start-maximized")
  # # options.add_argument('--window-size=1920,1080')
  # options.add_argument("--no-sandbox") # If you're running the project in Docker, you may also need to add 'no-sandbox' to Chrome's options: https://blog.phusion.nl/2018/05/24/using-chrome-headless-selenium-and-capybara-inside-gitlab-runner-and-docker/
  # options.add_argument("--disable-dev-shm-usage")
  # # options.add_argument("--log-path=/var/log/chromedriver.log")
  # # options.add_argument("--log-level=INFO")
  # # options.add_argument("--user-data-dir=/chromeuserdatadir")
  # options.add_argument("--disable-gpu")
  # options.add_argument("--headless") if ENV["CHROME_HEADLESS"] == "true"
  # options.add_argument("--enable-logging")
  # options.add_argument("--enable-features=NetworkService,NetworkServiceInProcess") # You may also notice the enable-features tag in chrome's options, this is a temporary fix because of an issue in Chrome 74 in which cookies get randomly cleared during execution, which might cause Chrome to freeze.
  # # options.add_argument("--user-agent=Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/91.0.4472.124 Safari/537.36")

  # options.add_preference(:download, {
  #   default_directory:    ENV["REMOTE_DOWNLOAD_DIR"],
  #   prompt_for_download:  false,
  #   directory_upgrade:    true,
  #   extensions_to_open:   ""
  # })
  # options.add_preference(:plugins, {
  #   plugins_disabled: ["Chrome PDF Viewer"]
  # })
  # options.logging_prefs = {
  #   browser: 'ALL',
  #   driver: 'ALL'
  # }

  Capybara::Selenium::Driver.new(
    app,
    browser: :remote,
    url: ENV["HUB_URL"],
    options: options,
    # capabilities: Selenium::WebDriver::Remote::Capabilities.chrome( # TODO
    #   loggingPrefs: {
    #     browser: 'ALL',
    #     driver: 'ALL'
    #   }
    # )

    # http_client: client,
  )
end

Capybara.default_driver = :selenium_chrome
Capybara.javascript_driver = :selenium_chrome
Capybara.default_max_wait_time = 10 # def - 2
Capybara.current_session.driver.browser.file_detector = nil
```

my config docker/chunks/selenium-and-tests-runner.yml

```yml
version: '2.3'

services:
  ## overriddings
  selenium-hub:
    image: selenium/hub:4.16.1-20231219
    environment:
      - SE_OPTS=--log-level FINEST
      # - SE_OPTS="--log-level=FINEST --debug"
      # - SE_OPTS="--debug"
      # - SE_OPTS="-Dselenium.LOGGER.level=INFO"
    # ports:
    #   - "4442:4442"
    #   - "4443:4443"
    #   - "4444:4444"

  chrome:
    # privileged: true # it will also make "shm_size = infinite"
    shm_size: 4gb
    # image: selenium/standalone-chrome:latest
    # image: selenium/standalone-chrome:118.0-20231016
    # image: selenium/standalone-chrome:113.0-20230508
    # image: selenium/standalone-chrome:beta
    image: selenium/node-chrome:4.16.1-20231219
    depends_on:
      - selenium-hub
    environment:
      - SE_EVENT_BUS_HOST=selenium-hub
      - SE_EVENT_BUS_PUBLISH_PORT=4442
      - SE_EVENT_BUS_SUBSCRIBE_PORT=4443
      # - SE_OPTS="--log-level=FINEST"
      - SE_OPTS=--log-level FINEST
      # - SE_OPTS="--debug"
      # - SE_OPTS="-Dselenium.LOGGER.level=INFO"
    command: >
      /bin/bash -c '
      sudo chown seluser /chrome-downloads /fixtures &&
      ls -al /chrome-downloads &&
      ls -al /fixtures &&
      df -h /dev/shm &&
      exec /opt/bin/entry_point.sh'
    volumes:
      # XXX
      # dirs should be accessible for seluser user,
      # that's why hack with chown above
      - downloads:/chrome-downloads
      # - /dev/shm:/dev/shm

  tests_runner:
    extends:
      file: base.yml
      service: be
    environment:
      # NOTE: `chrome` is passing donwload files to `tests_runner` through `downloads` volume
      REMOTE_DOWNLOAD_DIR: /chrome-downloads # directory, where `chrome` will save files
      LOCAL_DOWNLOAD_DIR: /tests-runner-downloads # directory, where `tests_runner` can find files, saved by `chrome`

      REMOTE_FIXTURES_DIR: /fixtures # directory, where `chrome` can find fixtures
    volumes:
      - downloads:/tests-runner-downloads
```

docker/tdd.yml

```yml
# INFO: it's like feature_tests, but for tdd

version: '2.3'

volumes:
  ## volumes without changes
  postgres_data:
  pgadmin_data:
  redis_data:
  filemanager_upload_data:
  carrierwave_private_upload_data:
  carrierwave_public_upload_data:
  carrierwave_cache_data:
  elasticsearch_data:
  be_gems:
    external:
      name: myapp_be_gems
  # and
  downloads:

networks:
  myapp_feature_tests:
    external: true

services:
  ## services without changes
  postgres:
    extends:
      file: chunks/base.yml
      service: postgres
    command: postgres -c log_statement=all
    env_file:
      - ./envs/postgres-credentials-local.env

  redis:
    extends:
      file: chunks/base.yml
      service: redis
    ports:
      - 6379:6379

  sidekiq:
    extends:
      file: chunks/base.yml
      service: sidekiq
    env_file:
      - ./envs/rails-environment-test.env
      - ./envs/database-url-local.env
      - ./envs/redis-worker-url-default.env
      - ./envs/carrierwave-dirs.env

      - ./envs/mail-config-test.env
      - ./secret-envs-local/mail-config-mailtrap.env
    environment:
      ROOT_URL: http://myapp_feature_tests_be:3000
      ELASTICSEARCH_BACKEND_URL: http://elasticsearch:9200

      NEW_GOOGLE_RECAPTCHA__DONT_INITIALIZE: "true"
    depends_on:
      - redis

  selenium-hub:
    extends:
      file: chunks/selenium-and-tests-runner.yml
      service: selenium-hub

  chrome:
    extends:
      file: chunks/selenium-and-tests-runner.yml
      service: chrome
    ports:
      # - "7900:7900" # novnc port
      - "5900:5900" # vnc port
    environment:
      SE_VNC_NO_PASSWORD: "true"
      SE_START_NO_VNC: "false"
      # xrandr | grep ' connected'
      SE_SCREEN_WIDTH: 2560
      SE_SCREEN_HEIGHT: 1600
      SE_NODE_SESSION_TIMEOUT: 99999999 # why chrome is exiting if I use pry? I do "docker logs vd-rails_tdd-chrome-1". I see "INFO [LocalNode.stopTimedOutSession] - Session id ZZZ timed out, stopping...". I check https://github.com/SeleniumHQ/docker-selenium/issues/1769 => prevent
    volumes:
      - ../spec/fixtures:/fixtures

  elasticsearch:
    extends:
      file: chunks/base.yml
      service: elasticsearch

  ## overriddings
  be:
    extends:
      file: chunks/base.yml
      service: be
    env_file:
      - ./envs/rails-environment-test.env
      - ./envs/database-url-local.env
      - ./envs/redis-worker-url-default.env
      - ./envs/carrierwave-dirs.env
      - ./envs/filemanager-access-key.env
      - ./envs/mail-config-test.env

      - ./secret-envs-local/recaptcha.env
      - ./secret-envs-local/stripe-test.env
      - ./secret-envs-local/usps.env
      - ./secret-envs-local/akismet-test.env
      - ./secret-envs-local/bing-api-key.env
    environment:
      ROOT_URL: http://myapp_feature_tests_be:3000

      # RAILS_ENV: "development"
      RAILS_ENABLE_CACHE: 'false'
      RAILS_LOG_TO_STDOUT: 'true'
      RAILS_SHOW_EXCEPTIONS_INSTEAD_OF_RAISE: 'true'

      # serve static files that are usually server by nginx with rack
      SERVE_CARRIERWAVE_DIRS_WITH_RACK: 'true'

      ELASTICSEARCH_FRONT_URL:   http://localhost:9200
      ELASTICSEARCH_BACKEND_URL: http://elasticsearch:9200
      ANALYTICS_ID:              dummy

      # NEW_GOOGLE_RECAPTCHA__DONT_INITIALIZE: 'true'
      # APP_RECAPTCHA__BLOCK_ONLY_IF_USERNAME_CONTAINS: "imambot"
      RECAPTCHA__TRANSFORM_BROWSER_ERROR_TO_SUCCESS: "true"
      SIDEKIQ__INLINE_JOBS: 'true'
    volumes:
      - carrierwave_public_upload_data:/public_upload
      - carrierwave_private_upload_data:/private_upload
      - carrierwave_cache_data:/carrierwave_cache
    networks:
      - default
      - myapp_feature_tests
    depends_on:
      - postgres
      - redis
      - sidekiq
      - elasticsearch
      - chrome

  tests_runner:
    extends:
      file: chunks/selenium-and-tests-runner.yml
      service: tests_runner
    command: >
      bash -c "
      waitforit -host=postgres -port=5432 -timeout=30 &&
      waitforit -host=selenium-hub -port=4444 -timeout=40 &&
      bundle exec guard"
    env_file:
      - ./envs/rails-environment-test.env
      - ./envs/database-url-local.env
      - ./envs/carrierwave-dirs.env
      - ./envs/mail-config-test.env
      - ./envs/redis-worker-url-default.env

      - ./secret-envs-local/stripe-test.env
      - ./secret-envs-local/akismet-test.env
      - ./secret-envs-local/usps.env
      - ./secret-envs-local/recaptcha.env
    environment:
      ROOT_URL: http://myapp_feature_tests_be:3000
      APP_HOST: http://myapp_feature_tests_be:3000
      HUB_URL:  http://selenium-hub:4444/wd/hub
      RECAPTCHA__DONT_INITIALIZE: 'true'

      RAILS_ENABLE_CACHE: 'false'
      RAILS_LOG_TO_STDOUT: 'false'
      RAILS_SHOW_EXCEPTIONS_INSTEAD_OF_RAISE: 'false'

      ENABLE_EMAILS_DEBUG: 'true'

      ELASTICSEARCH_FRONT_URL:   http://localhost:9200
      ELASTICSEARCH_BACKEND_URL: http://elasticsearch:9200
      ANALYTICS_ID:              dummy

      # NEW_GOOGLE_RECAPTCHA__DONT_INITIALIZE: "true"
      # APP_RECAPTCHA__BLOCK_ONLY_IF_USERNAME_CONTAINS: "imambot"
      CHROME_HEADLESS: 'false'
      SIDEKIQ__INLINE_JOBS: 'true'
    networks:
      - default
      - myapp_feature_tests
    volumes:
      # NOTE: should be same as in carrierwave-dirs.env
      - carrierwave_public_upload_data:/public_upload
      - carrierwave_private_upload_data:/private_upload
      - carrierwave_cache_data:/carrierwave_cache
    depends_on:
      - postgres
      - chrome
      - elasticsearch

#   pgadmin:
#     image: fenglc/pgadmin4
#     ports:
#       - 5050:5050
#     depends_on:
#       - postgres
```

I have a test

```rb
module Macroses
  module FeaturesAuthLogin
    extend self

    def visit_and_login(user_attributes)
      using_wait_time 30 do
        visit new_user_session_path
      end

      fill_login(user_attributes)
      click_login_button
    end

    def click_login_button
      within "#new_user" do
        find("[type=submit]").click
      end
    end

    def fill_login(data)
      within "#new_user" do
        fill_in "user[email]",    with: data[:email]
        fill_in "user[password]", with: data[:password]
      end
    end

    def expect_login_success
      # using_wait_time 30 do
      expect(page).to have_content("Signed in successfully")
      # end
    end
  end
end

feature "Admin audios page: show" do
  include require_module_relative("./lib")
  include Macroses::FeaturesAuthLogin
  extend  require_module_relative("../when_admin")

  when_admin

  before do
    visit_and_login(admin_attributes)
    expect_login_success
  end

  let!(:audio) do
    create_audio
  end

  scenario "can show audio" do
    visit admin_audio_path(audio)
    expect(page).to have_content(audio.title)
  end
end
```

it stops on `expect(page).to have_content("Signed in successfully")`

BUT THE TEXT IS THERE

its just selenium doesnt respond

![2024-01-07_18-31](https://github.com/SeleniumHQ/selenium/assets/7573215/655478d5-385c-4384-9ae9-df6bc181246e)

it gives error

```sh
  1) Admin audios page: edit can edit audio
     Got 0 failures and 2 other errors:

     1.1) Failure/Error: expect(page).to have_content("Signed in successfully")

          Net::ReadTimeout:
            Net::ReadTimeout with #<TCPSocket:(closed)>
          # /usr/local/bundle/gems/selenium-webdriver-4.16.0/lib/selenium/webdriver/remote/http/default.rb:118:in `response_for'
          # /usr/local/bundle/gems/selenium-webdriver-4.16.0/lib/selenium/webdriver/remote/http/default.rb:75:in `request'
          # /usr/local/bundle/gems/selenium-webdriver-4.16.0/lib/selenium/webdriver/remote/http/common.rb:59:in `call'
          # /usr/local/bundle/gems/selenium-webdriver-4.16.0/lib/selenium/webdriver/remote/bridge.rb:601:in `execute'
          # /usr/local/bundle/gems/selenium-webdriver-4.16.0/lib/selenium/webdriver/remote/bridge.rb:536:in `find_elements_by'
          # /usr/local/bundle/gems/selenium-webdriver-4.16.0/lib/selenium/webdriver/common/search_context.rb:78:in `find_elements'
          # /usr/local/bundle/gems/capybara-3.39.2/lib/capybara/selenium/extensions/find.rb:17:in `find_by'
          # /usr/local/bundle/gems/capybara-3.39.2/lib/capybara/selenium/extensions/find.rb:7:in `find_xpath'
          # /usr/local/bundle/gems/capybara-3.39.2/lib/capybara/node/base.rb:119:in `find_xpath'
          # /usr/local/bundle/gems/capybara-3.39.2/lib/capybara/queries/selector_query.rb:259:in `find_nodes_by_selector_format'
          # /usr/local/bundle/gems/capybara-3.39.2/lib/capybara/queries/selector_query.rb:166:in `block in resolve_for'
          # /usr/local/bundle/gems/capybara-3.39.2/lib/capybara/node/base.rb:77:in `synchronize'
          # /usr/local/bundle/gems/capybara-3.39.2/lib/capybara/queries/selector_query.rb:165:in `resolve_for'
          # /usr/local/bundle/gems/capybara-3.39.2/lib/capybara/node/finders.rb:303:in `block in synced_resolve'
          # /usr/local/bundle/gems/capybara-3.39.2/lib/capybara/node/base.rb:77:in `synchronize'
          # /usr/local/bundle/gems/capybara-3.39.2/lib/capybara/node/finders.rb:301:in `synced_resolve'
          # /usr/local/bundle/gems/capybara-3.39.2/lib/capybara/node/finders.rb:60:in `find'
          # /usr/local/bundle/gems/capybara-3.39.2/lib/capybara/node/document.rb:24:in `text'
          # /usr/local/bundle/gems/capybara-3.39.2/lib/capybara/queries/text_query.rb:108:in `text'
          # /usr/local/bundle/gems/capybara-3.39.2/lib/capybara/queries/text_query.rb:29:in `resolve_for'
          # /usr/local/bundle/gems/capybara-3.39.2/lib/capybara/node/matchers.rb:862:in `block in _verify_text'
          # /usr/local/bundle/gems/capybara-3.39.2/lib/capybara/node/base.rb:84:in `synchronize'
          # /usr/local/bundle/gems/capybara-3.39.2/lib/capybara/node/matchers.rb:861:in `_verify_text'
          # /usr/local/bundle/gems/capybara-3.39.2/lib/capybara/node/matchers.rb:676:in `assert_text'
          # /usr/local/bundle/gems/capybara-3.39.2/lib/capybara/session.rb:773:in `assert_text'
          # /usr/local/bundle/gems/capybara-3.39.2/lib/capybara/rspec/matchers/have_text.rb:10:in `element_matches?'
          # /usr/local/bundle/gems/capybara-3.39.2/lib/capybara/rspec/matchers/base.rb:52:in `matches?'
          # ./spec/macroses/features_auth_login.rb:33:in `expect_login_success'
          # ./spec/entries/feature/admin/audios/edit_spec.rb:10:in `block (2 levels) in <top (required)>'

     1.2) Failure/Error: (io = @io.to_io).wait_readable(@read_timeout) or raise Net::ReadTimeout.new(io)

          Net::ReadTimeout:
            Net::ReadTimeout with #<TCPSocket:(closed)>
          # /usr/local/bundle/gems/selenium-webdriver-4.16.0/lib/selenium/webdriver/remote/http/default.rb:118:in `response_for'
          # /usr/local/bundle/gems/selenium-webdriver-4.16.0/lib/selenium/webdriver/remote/http/default.rb:75:in `request'
          # /usr/local/bundle/gems/selenium-webdriver-4.16.0/lib/selenium/webdriver/remote/http/common.rb:59:in `call'
          # /usr/local/bundle/gems/selenium-webdriver-4.16.0/lib/selenium/webdriver/remote/bridge.rb:601:in `execute'
          # /usr/local/bundle/gems/selenium-webdriver-4.16.0/lib/selenium/webdriver/remote/bridge.rb:206:in `window_handles'
          # /usr/local/bundle/gems/selenium-webdriver-4.16.0/lib/selenium/webdriver/common/driver.rb:199:in `window_handles'
          # /usr/local/bundle/gems/capybara-3.39.2/lib/capybara/selenium/driver.rb:253:in `window_handles'
          # /usr/local/bundle/gems/capybara-3.39.2/lib/capybara/selenium/driver_specializations/chrome_driver.rb:40:in `reset!'
          # /usr/local/bundle/gems/capybara-3.39.2/lib/capybara/session.rb:131:in `reset!'
          # /usr/local/bundle/gems/capybara-3.39.2/lib/capybara.rb:327:in `block in reset_sessions!'
          # /usr/local/bundle/gems/capybara-3.39.2/lib/capybara.rb:327:in `reverse_each'
          # /usr/local/bundle/gems/capybara-3.39.2/lib/capybara.rb:327:in `reset_sessions!'
          # /usr/local/bundle/gems/capybara-3.39.2/lib/capybara/rspec.rb:20:in `block (2 levels) in <top (required)>'

```

-------------

can it be because of ?

```
docker run -it selenium/hub:4.16.1-20231219 bash
To run a command as administrator (user "root"), use "sudo <command>".
See "man sudo_root" for details.

WARNING: Very high value reported by "ulimit -n". Consider passing "--ulimit nofile=32768" to "docker run".
```

### How can we reproduce the issue?

see above (?)

### Relevant log output

my logs are below:
1. chrome container - head -n 1000 [chrome-head-1000.txt](https://github.com/SeleniumHQ/selenium/files/13853231/chrome-head-1000.txt)
1. chrome container - relevant [chrome-relevant.txt](https://github.com/SeleniumHQ/selenium/files/13853226/chrome-relevant.txt)
1. hub container    - head -n 1000 [hub-head-1000.txt](https://github.com/SeleniumHQ/selenium/files/13853230/hub-head-1000.txt)
1. hub container    - relevant [hub-relevant.txt](https://github.com/SeleniumHQ/selenium/files/13853233/hub-relevant.txt)

### Operating System

nixos with docker

### Selenium version

selenium/node-chrome:4.16.1-20231219 and selenium/hub:4.16.1-20231219

### What are the browser(s) and version(s) where you see this issue?

chrome 120.0

### What are the browser driver(s) and version(s) where you see this issue?

chrome

### Are you using Selenium Grid?

no
