### ISSUE TITLE
[🐛 Bug]: Exception launching node using default node.toml

### ISSUE THREAD

**Issue by devqaio** [SeleniumHQ/selenium#13518]
### What happened?

I had created node.toml from sever jar from commandline using java -jar server.jar node -config. When I use the same toml to launch node, it throws lint error

### How can we reproduce the issue?

```shell
execute java -jar sever.jar node --config-file node.toml
```

### Relevant log output

```shell
java.lang.reflect.InvocationTargetException
        at java.base/jdk.internal.reflect.DirectMethodHandleAccessor.invoke(DirectMethodHandleAccessor.java:119)
        at java.base/java.lang.reflect.Method.invoke(Method.java:578)
        at org.openqa.selenium.grid.Bootstrap.runMain(Bootstrap.java:77)
        at org.openqa.selenium.grid.Bootstrap.main(Bootstrap.java:70)
Caused by: org.openqa.selenium.grid.config.ConfigException: null
 Validate the config using https://www.toml-lint.com/.
 Refer to https://toml.io/en/ for TOML usage guidance.
        at org.openqa.selenium.grid.config.TomlConfig.<init>(TomlConfig.java
[node.txt](https://github.com/SeleniumHQ/selenium/files/14070594/node.txt)
:47)
        at org.openqa.selenium.grid.config.TomlConfig.from(TomlConfig.java:57)
        at org.openqa.selenium.grid.config.Configs.from(Configs.java:39)
        at java.base/java.util.stream.ReferencePipeline$3$1.accept(ReferencePipeline.java:197)
        at java.base/java.util.ArrayList$ArrayListSpliterator.forEachRemaining(ArrayList.java:1625)
        at java.base/java.util.stream.AbstractPipeline.copyInto(AbstractPipeline.java:509)
        at java.base/java.util.stream.AbstractPipeline.wrapAndCopyInto(AbstractPipeline.java:499)
        at java.base/java.util.stream.AbstractPipeline.evaluate(AbstractPipeline.java:575)
        at java.base/java.util.stream.AbstractPipeline.evaluateToArrayNode(AbstractPipeline.java:260)
        at java.base/java.util.stream.ReferencePipeline.toArray(ReferencePipeline.java:616)
        at org.openqa.selenium.grid.config.ConfigFlags.readConfigFiles(ConfigFlags.java:67)
        at org.openqa.selenium.grid.TemplateGridCommand.lambda$configure$4(TemplateGridCommand.java:98)
        at org.openqa.selenium.grid.Main.launch(Main.java:83)
        at org.openqa.selenium.grid.Main.go(Main.java:56)
        at org.openqa.selenium.grid.Main.main(Main.java:41)
        at java.base/jdk.internal.reflect.DirectMethodHandleAccessor.invoke(DirectMethodHandleAccessor.java:104)
        ... 3 more
```

### Operating System

Windows 11

### Selenium version

4.16.1 - Java

### What are the browser(s) and version(s) where you see this issue?

All

### What are the browser driver(s) and version(s) where you see this issue?

All

### Are you using Selenium Grid?

4.16.1

**Comment by devqaio** [comment]
[node.txt](https://github.com/SeleniumHQ/selenium/files/14070598/node.txt)

**Comment by diemol** [comment]
Please use https://www.toml-lint.com/ to verify the toml file, let us know how it goes.

**Comment by devqaio** [comment]
@diemol - The linter says "_Error on line 146: Can't redefine existing key at row 147, col 17, pos 5514: 146: # Example: 147> max-sessions = 8 ^ 148:_".  Under node, I have max session as 8. However for node.driver-configuration, It is being set to 2 as I need to enable only 2 session for Firefox.

**Comment by devqaio** [comment]
My current driver configuration has 
```
[[node.driver-configuration]]
display-name = "Firefox Nightly"
webdriver-executable = "/usr/local/bin/geckodriver"
max-sessions = 2
stereotype = "{\"browserName\": \"firefox\", \"browserVersion\": \"86\", \"moz:firefoxOptions\": {\"binary\":\"/Applications/Firefox Nightly.app/Contents/MacOS/firefox-bin\"}}"
```
However, if I need to enable Chrome/Edge along with Firefox, should I need to repeat the complete section updating the parameter (as below)? If yes, then will it not create conflict as all keys will be repeated.

```
[[node.driver-configuration]]
display-name = "Firefox Nightly"
webdriver-executable = "/usr/local/bin/geckodriver"
max-sessions = 2
stereotype = "{\"browserName\": \"firefox\", \"browserVersion\": \"86\", \"moz:firefoxOptions\": {\"binary\":\"/Applications/Firefox Nightly.app/Contents/MacOS/firefox-bin\"}}"

[[node.driver-configuration]]
display-name = "Chrome Nightly"
webdriver-executable = "/usr/local/bin/chromedriver"
max-sessions = 4
stereotype = "{\"browserName\": \"chrome\", \"browserVersion\": \"115\"}"
```

My requirement here is the node should support 2 parallel sessions on firefox and 4 sessions from chrome. Considering I have a 8-core processor, I keep the remaining 2 on hold to enable for Edge as required.

**Comment by diemol** [comment]
Why don't you share the whole file so I can understand better what you are trying to do?

**Comment by devqaio** [comment]
@diemol : Attached the toml content..
[node.txt](https://github.com/SeleniumHQ/selenium/files/14083018/node.txt)

**Comment by diemol** [comment]
Can you simplify it and just configure what you need?

**Comment by devqaio** [comment]
@diemol Attached is simplified node.toml content

[node-simplified.txt](https://github.com/SeleniumHQ/selenium/files/14124283/node-simplified.txt)

**Comment by devqaio** [comment]
If I comment out "max-sessions = 8", it starts the node but it doesn't register the node to hub. As both hub and node are being configured in same laptop, I rule out the firewall issue for traffic.
![image](https://github.com/SeleniumHQ/selenium/assets/10003447/5d1a2e0a-db53-4bf6-8e3d-4d0e3bce7e9d)
[hub.txt](https://github.com/SeleniumHQ/selenium/files/14124477/hub.txt)

**Comment by diemol** [comment]
But you have several options with the default value in your provided file. Why is this needed? It makes reading the file very hard.

In any case, you are redefining `max-sessions` under the same `[[node.driver-configuration]]`. Move those to the end of the `[node]` section.

I cannot validate anything else because you have a custom driver factory:
```
driver-factories = ["org.openqa.selenium.example.LynxDriverFactory"]
```

In any case, here is a valid toml file:

```toml
[server]
# Whether the Selenium server should allow web browser connections from any host
# Type: boolean
# Default: false
# Example: 
allow-cors = false

# Whether the server should bind to the host address/name, or only use it to report its reachable url. Helpful in complex network topologies where the server cannot report itself with the current IP/hostname but rather an external IP or hostname (e.g. inside a Docker container).
# Type: boolean
# Default: true
# Example: 
bind-host = true

# Maximum number of listener threads. Default value is: (available processors) * 3.
# Type: int
# Default: 0
# Example: 
max-threads = 12

# Port to listen on. There is no default as this parameter is used by different components, for example Router/Hub/Standalone will use 4444 and Node will use 5555.
# Type: integer
# Example: 
port = 5555

[node]
# Autodetect which drivers are available on the current system, and add them to the Node.
# Type: boolean
# Default: true
# Example: 
detect-drivers = false

# Drain and shutdown the Node after X sessions have been executed. Useful for environments like Kubernetes. A value higher than zero enables this feature.
# Type: int
# Default: 0
# Example: 
drain-after-session-count = 1

# Mapping of fully qualified class name to a browser configuration that this matches against. --driver-factory org.openqa.selenium.example.LynxDriverFactory '{"browserName": "lynx"}'
# Type: list of strings
# Example: 
driver-factories = ["org.openqa.selenium.example.LynxDriverFactory"]

# Drivers that should be checked. If specified, will skip autoconfiguration. Example: -I "firefox" -I "chrome"
# Type: list of strings
# Default: []
# Example: 
driver-implementation = ["firefox", "chrome"]

# Enable BiDi proxying in Grid. A Grid admin can disable BiDi if the network does not allow websockets. True by default
# Type: boolean
# Default: true
# Example: 
enable-bidi = true

# Enable CDP proxying in Grid. A Grid admin can disable CDP if the network does not allow websockets. True by default
# Type: boolean
# Default: true
# Example: 
enable-cdp = true

# When enabled, the Grid node will automatically do the following: 1. Creates a temporary directory which will now represent the directory into which files downloaded by Chrome/Firefox/Edge browser will be under. 2. For every new session, a sub-directory will be created/deleted so that all files that were downloaded for a given session are stored in.
# Type: boolean
# Example: 
enable-managed-downloads = false

# How often, in seconds, will the Node send heartbeat events to the Distributor to inform it that the Node is up.
# Type: int
# Default: 60
# Example: 
heartbeat-period = 60

# Full classname of non-default Node implementation. This is used to manage a session's lifecycle.
# Type: string
# Default: org.openqa.selenium.grid.node.local.LocalNodeFactory
# Example: 
implementation = "org.openqa.selenium.grid.node.local.LocalNodeFactory"

# Maximum number of concurrent sessions. Default value is the number of available processors.
# Type: int
# Default: 8
# Example: 
max-sessions = 8

# The # of available processors is the recommended max sessions value (1 browser session per processor). Setting this flag to true allows the recommended max value to be overwritten. Session stability and reliability might suffer as the host could run out of resources.
# Type: boolean
# Default: false
# Example: 
override-max-sessions = false

# How often, in seconds, the Node will try to register itself for the first time to the Distributor.
# Type: int
# Default: 10
# Example: 
register-cycle = 10

# How long, in seconds, will the Node try to register to the Distributor for the first time. After this period is completed, the Node will not attempt to register again.
# Type: int
# Default: 120
# Example: 
register-period = 120

# When drivers are not available on the current system, use, Selenium Manager.
# Type: boolean
# Default: false
# Example: 
selenium-manager = false

# Let X be the session-timeout in seconds. The Node will automatically kill a session that has not had any activity in the last X seconds. This will release the slot for other tests.
# Type: int
# Default: 300
# Example: 
session-timeout = 300

# Environment variable to check in order to determine if a vnc stream is available or not.
# Type: string
# Default: SE_START_XVFB
# Example: 
vnc-env-var = "SE_START_XVFB"

# List of configured drivers a Node supports. It is recommended to provide this type of configuration through a toml config file to improve readability. Command line example: --drivers-configuration display-name="Firefox Nightly" max-sessions=2 webdriver-path="/usr/local/bin/geckodriver" stereotype='{"browserName": "firefox", "browserVersion": "86", "moz:firefoxOptions": {"binary":"/Applications/Firefox Nightly.app/Contents/MacOS/firefox-bin"}}'
# Type: list of strings
# Example: 
[[node.driver-configuration]]
display-name = "Firefox Nightly"
webdriver-executable = "/usr/local/bin/geckodriver"
max-sessions = 2
stereotype = "{\"browserName\": \"firefox\", \"browserVersion\": \"86\"}"

[[node.driver-configuration]]
display-name = "Chrome Nightly"
webdriver-executable = "/usr/local/bin/chromedriver"
max-sessions = 4
stereotype = "{\"browserName\": \"chrome\", \"browserVersion\": \"109\"}"


[logging]
# Enable http logging. Tracing should be enabled to log http logs.
# Type: boolean
# Default: false
# Example: 
http-logs = false

# Log encoding
# Type: string
# Example: 
log-encoding = "UTF-8"

# Log level. Default logging level is INFO. Log levels are described here https://docs.oracle.com/javase/7/docs/api/java/util/logging/Level.html
# Type: string
# Default: INFO
# Example: 
log-level = "INFO"

# Format of the timestamp in log output
# Type: string
# Example: 
log-timestamp-format = "HH:mm:ss.SSS"

# Use plain log lines
# Type: boolean
# Default: true
# Example: 
plain-logs = true

# Use structured logs
# Type: boolean
# Default: false
# Example: 
structured-logs = false

# Enable trace collection
# Type: boolean
# Default: true
# Example: 
tracing = true

[events]
# Whether the connection string should be bound or connected. When true, the component will be bound to the Event Bus (as in the Event Bus will also be started by the component, typically by the Distributor and the Hub). When false, the component will connect to the Event Bus.
# Type: boolean
# Example: 
bind = false

# Full classname of non-default event bus implementation
# Type: string
# Example: 
implementation = "org.openqa.selenium.events.zeromq.ZeroMqEventBus"

# Connection string for publishing events to the event bus
# Type: string
# Example: 
publish = "tcp://*:1233"

# Connection string for subscribing to events from the event bus
# Type: string
# Example: 
subscribe = "tcp://*:1232"
```
