### ISSUE TITLE
[🐛 Bug]: Unable to remote shutdown grid

### ISSUE THREAD

**Issue by panzli** [SeleniumHQ/selenium#13515]
### What happened?

Like in https://github.com/SeleniumHQ/selenium/issues/2852#issuecomment-250841027 I tried to shutdown the server from remote, but this isn't working and I found no docs about this.

### How can we reproduce the issue?

```shell
Running docker container `'selenium/standalone-chrome:latest'`
and execute 


curl  "http://localhost:4444/extra/LifecycleServlet?action=shutdown
curl http://localhost:4444/lifecycle-manager?action=shutdown
``
```

### Relevant log output

```shell
{
  "value": {
    "error": "unknown command",
    "message": "Unable to find handler for (GET) \u002flifecycle-manager",
    "stacktrace": ""
  }



{
  "value": {
    "error": "unknown command",
    "message": "Unable to find handler for (GET) \u002fselenium-server\u002fdriver\u002f",
    "stacktrace": ""
  }
}



``
```

### Operating System

Ubuntu 22.04 

### Selenium version

        "version": "4.16.1 (revision 9b4c83354e)",

### What are the browser(s) and version(s) where you see this issue?

terminal

### What are the browser driver(s) and version(s) where you see this issue?

terminal

### Are you using Selenium Grid?

        "version": "4.16.1 (revision 9b4c83354e)",

**Comment by pujagani** [comment]
The comment linked in the issue points to the old version of Selenium. Those endpoints are not valid in Selenium 4. I glanced at the current codebase and could not find a way to do the same in the latest version. I might be missing something. @diemol Appreciate your insights here.

**Comment by diemol** [comment]
This was never added to Grid 4 because it was a security concern. There are now other mechanisms to stop a Node or Standalone, what is your use case?

**Comment by krmahadevan** [comment]
We can perhaps make use of the [drain](https://www.selenium.dev/documentation/grid/advanced_features/endpoints/#drain-node) end-point to shutdown the node ?  Since the drain-node requires to know which node, maybe we can use the [Grid Status](https://www.selenium.dev/documentation/grid/advanced_features/endpoints/#grid-status) end-point to retrieve the node to which the session belongs to ?

**Comment by panzli** [comment]
Thanks for the report, I want to shutdown the standalone-chrome docker, If my Python script ist suceeded.

**Comment by krmahadevan** [comment]
@panzli - Why not just kill the docker container itself instead of shutting down the standalone chrome java binary ?

**Comment by diemol** [comment]
If you are using Standalone, you can use the drain endpoint to shutdown the Node and therefore the Grid when you are done.

**Comment by panzli** [comment]
Initially this should be my resolution, the docker container spawns unattended each day with cron and I do'nt want a 24/7 idle container.

```
version: '3.9'
services:

  standalone-chrome:
    container_name: "${CHROME_CONTAINER_NAME}"
    image: 'selenium/standalone-chrome:latest'
    shm_size: 2g
    ports:
      - '7900'
    env_file: standalone-chrome.env
    networks:
      - selenium-network
    healthcheck:
      test: ["CMD-SHELL", "curl -f http://standalone-chrome:4444/wd/hub/status | jq -e '.value.ready == true'"]
      interval: 5s
      timeout: 5s
      retries: 10



  ihk-runner:
    container_name: "${SELENIUM_CONTAINER_NAME}"
    build: .
    volumes:
      - ./scripts:/scripts
    command: /bin/sh -c 'find /scripts -name *.py -exec python3 {} \; && curl  "http://${CHROME_CONTAINER_NAME}:4444/extra/LifecycleServlet?action=shutdown"'
    env_file: selenium-runner.env
    environment:
      - CHROME_CONTAINER_NAME=${CHROME_CONTAINER_NAME}
    depends_on: 
      standalone-chrome:
        condition: service_healthy
    networks:
      - selenium-network

networks:
  selenium-network:
    driver: bridge

```
