### ISSUE TITLE
[🐛 Bug]: Unable to set the Custom Capabilities 

### ISSUE THREAD

**Issue by abhi-iac** [SeleniumHQ/selenium#14576]
### What happened?

**Current setup**: We are adding new nodes to the hub and want to add the custom capabilities to the node so that automation engineers can hit those nodes.

I have followed the this documentation: https://www.selenium.dev/documentation/grid/configuration/toml_options/#setting-custom-capabilities-for-matching-specific-nodes
When I am trying to perform tests with the custom capabilities my tests are not hitting the expected node (**Node 1**), instead it is hitting **node 2**

Tried couple of attempts.

**Node 1: Toml file**
```toml
[node]
detect-drivers = true

[[node.driver-configuration]]
display-name = "chrome"
stereotype = '{"browserName": "chrome", "browserVersion": "130.0.1", "networkname:applicationName": "dev_v4", "nodename:applicationName": "cust_v4" }'
max-sessions = 5
```

**Node 2: Toml file**
```toml
[node]
detect-drivers = true

[[node.driver-configuration]]
display-name = "chrome"
stereotype = '{"browserName": "chrome", "networkname:applicationName":"dev_v3", "nodename:applicationName":"cust_v3" }'
max-sessions = 5
```

I am calling the Load chrome driver as below

```csharp
private void LoadChromeDriver()
{
    var GridServer = Environment.GetEnvironmentVariable("Unum_Remote_seleniumGridServer");
    if (string.IsNullOrEmpty(GridServer))
    {
        GridServer = ConfigurationManager.AppSettings.seleniumGridServer.ToString();
    }
    if (ConfigurationManager.AppSettings.REMOTE == "true")
    {
        ChromeOptions chromeOptions = new ChromeOptions();
        chromeOptions.AddArgument("--start-maximized");
        chromeOptions.AddArgument("--window-size=1920,1080");
        chromeOptions.AddArgument("disable-dev-shm-usage");
        chromeOptions.AddArgument("lang=en-GB");
        chromeOptions.AddArgument("--disable-gpu");
        chromeOptions.AddArgument("--incognito");
        chromeOptions.AddArgument("--disable-web-security");
        chromeOptions.AddAdditionalOption("gsg:customcap", true);
        chromeOptions.AddAdditionalOption("networkname:applicationName", "dev_v4");
        chromeOptions.AddAdditionalOption("nodename:applicationName", "cust_v4");

        Driver = new RemoteWebDriver(new Uri(GridServer), chromeOptions.ToCapabilities(), TimeSpan.FromSeconds(120));

        _objectContainer.RegisterInstanceAs(Driver);
        Driver.Manage().Window.Maximize();
    }
    else
    {
        ChromeOptions chromeOptions = new ChromeOptions();
        chromeOptions.AddArgument("--start-maximized");
        chromeOptions.AddArgument("--window-size=1920,1080");
        chromeOptions.AddArgument("--incognito");
        Driver = new ChromeDriver(Path.GetDirectoryName(Assembly.GetExecutingAssembly().Location), chromeOptions, TimeSpan.FromMinutes(3));
        _objectContainer.RegisterInstanceAs(Driver);
        Driver.Manage().Window.Maximize();
    }
}
```

### How can we reproduce the issue?

```shell
If you copy my two toml files onto two different nodes and use my ChromeDriver method you should be able to replicate the issue
```

### Relevant log output

```shell
No logs
```

### Operating System

Windows server 2019 Datacenter

### Selenium version

openjdk 11.0.16.1 2022-08-12 LTS

### What are the browser(s) and version(s) where you see this issue?

Chrome 130.0.1

### What are the browser driver(s) and version(s) where you see this issue?

Chrome Driver 129.6668.89

### Are you using Selenium Grid?

Selenium grid 4..24.0

**Comment by abhi-iac** [comment]
Adding the sessions JSON, you can see I am calling **dev_4** custom cap node but executing on **dev_v3** node

```json
{
  "acceptInsecureCerts": false,
  "browserName": "chrome",
  "browserVersion": "129.0.6668.71",
  "chrome": {
    "chromedriverVersion": "129.0.6668.70 (df87d5cf12b1397be7495a04cab2db6239b227a8-refs/branch-heads/6668@{#1420})",
    "userDataDir": "C:\\Users\\xxxx\\AppData\\Local\\Temp\\scoped_dir6516_1266908807"
  },
  "fedcm:accounts": true,
  "goog:chromeOptions": {
    "debuggerAddress": "localhost:49166"
  },
  "gsg:customcap": true,
  "networkConnectionEnabled": false,
  "networkname:applicationName": "dev_v4",
  "nodename:applicationName": "cust_v4",
  "pageLoadStrategy": "normal",
  "platformName": "Windows XP",
  "proxy": {},
  "se:bidiEnabled": false,
  "se:cdp": "ws://x.x.x.x:4444/session/1bd1d7aa22ac5083a82f39e61cd177ff/se/cdp",
  "se:cdpVersion": "129.0.6668.71",
  "setWindowRect": true,
  "strictFileInteractability": false,
  "timeouts": {
    "implicit": 0,
    "pageLoad": 300000,
    "script": 30000
  },
  "unhandledPromptBehavior": "dismiss and notify",
  "webauthn:extension:credBlob": true,
  "webauthn:extension:largeBlob": true,
  "webauthn:extension:minPinLength": true,
  "webauthn:extension:prf": true,
  "webauthn:virtualAuthenticators": true
}
```

**Comment by VietND96** [comment]
Can you try to use a custom caps with prefix `se:`, for example: `se:dev_v3`

**Comment by abhi-iac** [comment]
Tried but no luck,

Chromedriver
chromeOptions.AddAdditionalOption("networkname:applicationName", "se:dev_v3");

TOML file
Node 2: Toml file
[node]
detect-drivers = true

[[node.driver-configuration]]
display-name = "chrome"
stereotype = '{"browserName": "chrome", "networkname:applicationName":"se:dev_v3", "nodename:applicationName":"cust_v3" }'
max-sessions = 5

Couple of possibilities tried.
With se:dev_v3 in toml file and without the se:dev_v3

**Comment by VietND96** [comment]
No, it should be a cap with key is `se:your_key` and value up to you. For example.

```
Chromedriver
chromeOptions.AddAdditionalOption("se:applicationName", "dev_v3");
```

```
TOML file
Node 2: Toml file
[node]
detect-drivers = true

[[node.driver-configuration]]
display-name = "chrome"
stereotype = '{"browserName": "chrome", "se:applicationName":"dev_v3", "se:applicationName":"cust_v3" }'
max-sessions = 5
```

**Comment by abhi-iac** [comment]
ChromeDriver
`chromeOptions.AddAdditionalOption("se:applicationName", "cust_v3");`

Toml
```toml
[node]
detect-drivers = true
[[node.driver-configuration]]
display-name = "chrome"
stereotype = '{"browserName": "chrome", "se:applicationName": "dev_v3", "se:applicationName": "cust_v3"}'
max-sessions = 5
````

Your snippet has two "se:applicationName" where as ideally it will be nodename: and network: name. As we are replaced those with se: don't we need to pass only  one "se:applicationName":"dev_v3" ?
`stereotype = '{"browserName": "chrome", "se:applicationName":"dev_v3", "se:applicationName":"cust_v3" }'`

After running tests with the changes, I can still see sessions are executing on node1. Any other workarounds?
