### ISSUE TITLE
[Facebook\WebDriver\Exception\UnknownServerException] Could not find ephemeral port to use

### ISSUE THREAD

**Issue by freinn** [SeleniumHQ/selenium#1485]
This is my Codeception configuration file:    

```
class_name: AcceptanceTester
    modules:
        enabled:
            - \Helper\Acceptance
            - WebDriver:
                url: 'https://www.forocoches.com' # proyecto-real.localhost/
                browser: chrome
                # http_proxy: direct # solves the proxy error on this version
                window_size: 1366x768
                wait: 10
                # http_proxy_port: '4444'

env:
    chrome:
        modules:
            config:
                WebDriver:
                    browser: 'chrome'
```

I've updated my chrome version to 47.0.2526.106 (64-bit), but I don't find enough information about that error. Also I'm using the last chromedriver and calling selenium this way:

```
java -jar selenium-server-standalone-2.49.0.jar -Dwebdriver.chrome.driver=browser_drivers/chromedriver
```

The error I get is:

```
[Facebook\WebDriver\Exception\UnknownServerException] Could not find ephemeral port to use
```
