### ISSUE TITLE
[🐛 Bug]: 4.28 does not start noVNC sessions correctly

### ISSUE THREAD

**Issue by parholmdahl** [SeleniumHQ/selenium#15131]
### What happened?

No NoVNC session can be viewed from GUI in version 4.28 of hub.

Resulting in console error: 

![Image](https://github.com/user-attachments/assets/ef0521c6-155a-4cff-a3ad-96442aef617f)

### How can we reproduce the issue?

```shell
1. Upgrade Grid and nodes to 4.28
2. Run a session that takes some time, so that you can look into the session
3. Go to selenium hub GUI and session page. 
4. Click on the camera icon.

Observe that the whole page get's white, and an error in the console log appears.
```

### Relevant log output

```shell
Uncaught TypeError: dh.default is not a constructor at x (LiveView:tsx:63:20) at LiveView.ts:77:5
```

### Operating System

MacOS

### Selenium version

4.28.0

### What are the browser(s) and version(s) where you see this issue?

Latest Chrome and Safari

### What are the browser driver(s) and version(s) where you see this issue?

Latest Chromedriver

### Are you using Selenium Grid?

Yes. 4.28

**Comment by vcc-ehemdal** [comment]
We're experiencing the same issue.

A minimal `docker-compose.yml` that demonstrates the issue:
```yaml
services:
  chrome:
    image: selenium/node-chrome:132.0
    shm_size: 2gb
    depends_on:
      - selenium-hub
    environment:
      - SE_EVENT_BUS_HOST=selenium-hub
      - SE_EVENT_BUS_PUBLISH_PORT=4442
      - SE_EVENT_BUS_SUBSCRIBE_PORT=4443
    entrypoint: bash -c 'SE_OPTS="--host $$HOSTNAME" /opt/bin/entry_point.sh'

  selenium-hub:
    image: selenium/hub:4.28
    ports:
      - "4442:4442"
      - "4443:4443"
      - "4444:4444"
```

A minimal Python example just to get a session rolling:
```python
import time
from selenium import webdriver

def main():
    print("Starting the remote session")
    driver = webdriver.Remote("http://localhost:4444/wd/hub", options=webdriver.ChromeOptions())
    print("Navigating")
    driver.get("https://www.google.com")
    print("Sleeping for 60 seconds")
    try:
        time.sleep(60)
    except KeyboardInterrupt:
        pass
    print("Closing the browser")
    driver.quit()


if __name__ == "__main__":
    main()
```
