### ISSUE TITLE
ffi gem fails to build

### ISSUE THREAD

**Issue by schurig** [SeleniumHQ/selenium#4413]
I'm trying to use the `selenium-webdriver` in a docker-container on my raspberry pi. But when Building the container I receive an error that a dependency of `selenium-webdriver` can't be installed.

```Dockerfile
# Dockerfile
FROM knjcode/rpi-ruby

# Set the locale
RUN apt-get clean && apt-get update && apt-get install -y locales
RUN locale-gen en_US.UTF-8 && \
    localedef -i en_US -f UTF-8 en_US.UTF-8 && \
    update-locale LANG=en_US.UTF-8
ENV LANG=en_US.UTF-8 \
    LANGUAGE=en_US:en \
    LC_ALL=en_US.UTF-8

RUN mkdir /usr/app
WORKDIR /usr/app

ADD Gemfile /usr/app/Gemfile
ADD Gemfile.lock /usr/app/Gemfile.lock
RUN bundle install

ADD . /usr/app

CMD ruby /usr/app/importer.rb
```

```yml
# docker-compose.yml
version: "2"
services:
  selenium-chrome:
    image: selenium/standalone-chrome
    ports:
      - "4444:4444"
    volumes:
      - /dev/shm:/dev/shm
      - ./downloads:/home/seluser/Downloads
  ruby:
    container_name: ruby
    build:
      context: .
    volumes:
      - ./export:/usr/app/export
      - ./downloads:/root/Downloads
    shm_size: 2g
    depends_on:
      - selenium-chrome
    command: "ruby /usr/app/importer.rb"
```

```ruby
# Gemfile

source 'https://rubygems.org'

gem 'selenium-webdriver'
gem 'twentysix'
```

When building the Docker-container I get the following error:

```bash
Step 11/13 : RUN bundle install
 ---> Running in 942ebb1f2510
Warning: the running version of Bundler (1.14.6) is older than the version that created the lockfile (1.15.3). We suggest you upgrade to the latest version of Bundler by running `gem install bundler`.
Fetching gem metadata from https://rubygems.org/...........
Fetching version metadata from https://rubygems.org/.
Installing ffi 1.9.18 with native extensions
Installing deep_merge 1.1.1
Installing multi_xml 0.6.0
Installing rubyzip 1.2.1
Using bundler 1.14.6
Gem::Ext::BuildError: ERROR: Failed to build gem native extension.

    current directory: /usr/local/bundle/gems/ffi-1.9.18/ext/ffi_c
/usr/local/bin/ruby -r ./siteconf20170806-7-ykqcpg.rb extconf.rb
checking for ffi.h... *** extconf.rb failed ***
Could not create Makefile due to some reason, probably lack of necessary
libraries and/or headers.  Check the mkmf.log file for more details.  You may
need configuration options.

Provided configuration options:
	--with-opt-dir
	--without-opt-dir
	--with-opt-include
	--without-opt-include=${opt-dir}/include
	--with-opt-lib
	--without-opt-lib=${opt-dir}/lib
	--with-make-prog
	--without-make-prog
	--srcdir=.
	--curdir
	--ruby=/usr/local/bin/$(RUBY_BASE_NAME)
	--with-ffi_c-dir
	--without-ffi_c-dir
	--with-ffi_c-include
	--without-ffi_c-include=${ffi_c-dir}/include
	--with-ffi_c-lib
	--without-ffi_c-lib=${ffi_c-dir}/lib
	--with-libffi-config
	--without-libffi-config
	--with-pkg-config
	--without-pkg-config
/usr/local/lib/ruby/2.4.0/mkmf.rb:457:in `try_do': The compiler failed to
generate an executable file. (RuntimeError)
You have to install development tools first.
	from /usr/local/lib/ruby/2.4.0/mkmf.rb:588:in `try_cpp'
	from /usr/local/lib/ruby/2.4.0/mkmf.rb:1095:in `block in have_header'
	from /usr/local/lib/ruby/2.4.0/mkmf.rb:945:in `block in checking_for'
	from /usr/local/lib/ruby/2.4.0/mkmf.rb:351:in `block (2 levels) in postpone'
	from /usr/local/lib/ruby/2.4.0/mkmf.rb:321:in `open'
	from /usr/local/lib/ruby/2.4.0/mkmf.rb:351:in `block in postpone'
	from /usr/local/lib/ruby/2.4.0/mkmf.rb:321:in `open'
	from /usr/local/lib/ruby/2.4.0/mkmf.rb:347:in `postpone'
	from /usr/local/lib/ruby/2.4.0/mkmf.rb:944:in `checking_for'
	from /usr/local/lib/ruby/2.4.0/mkmf.rb:1094:in `have_header'
	from extconf.rb:16:in `<main>'

To see why this extension failed to compile, please check the mkmf.log which can
be found here:

  /usr/local/bundle/extensions/armv7l-linux/2.4.0/ffi-1.9.18/mkmf.log

extconf failed, exit code 1

Gem files will remain installed in /usr/local/bundle/gems/ffi-1.9.18 for
inspection.
Results logged to
/usr/local/bundle/extensions/armv7l-linux/2.4.0/ffi-1.9.18/gem_make.out

An error occurred while installing ffi (1.9.18), and Bundler cannot continue.
Make sure that `gem install ffi -v '1.9.18'` succeeds before bundling.
ERROR: Service 'ruby' failed to build: The command '/bin/sh -c bundle install' returned a non-zero code: 5
```

What do I need to do to get the gem `selenium-webdriver` running on my raspberry pi (inside a docker-container)? Am I missing something here?
