### ISSUE TITLE
Allow to change what IP address is registered to grid

### ISSUE THREAD

**Issue by mikk150** [SeleniumHQ/selenium#7302]
## 🐛 Bug Report

selenium-node does not allow user to specify non-machine IP address to register

## To Reproduce

Detailed steps to reproduce the behavior:

1. create selenium hub on one machine
2. create VM on another machine to run browsers in, set networking to NAT, make sure to tell your virtualisation env to listen to selenium node port and send it to VM
3. try to register browser in VM to selenium hub and set `-host` to IP address of VM's host machine address (this could even be changed to `-registrationhost` or whatever if it is going to be implemented)

## Expected behavior

Node is registered to grid

## Test script or set of commands reproducing this issue

```yaml
version: "2.4"
services:
  selenium:
    image: selenium/hub
    networks:
     - selenium-network
    ports:
      - 4444:4444
  windows_10: #this is the machine I am trying to register to grid
    image: tianon/qemu
    # Increase scale number if needed
    networks:
      - selenium-network
    devices:
      - "/dev/kvm:/dev/kvm"
    ports:
      - 5900
    volumes:
      - ./config/windows/hda.qcow2:/tmp/hda.qcow2
      - /usr/share/ovmf/OVMF.fd:/tmp/OVMF.fd:ro
    command: start-qemu -bios /tmp/OVMF.fd -usbdevice tablet
    environment:
      - QEMU_HDA=/tmp/hda.qcow2
      - QEMU_CPU=2
      - QEMU_RAM=4096
      - QEMU_PORTS=5555 4444

networks:
  selenium-network:
```

```
java -Dwebdriver.ie.driver=IEDriverServer.exe -jar selenium-server-standalone-3.141.59.jar -port 5555 -host windows_10. -role node -hub http://selenium.:4444/grid/register -browser "browserName=internet explorer,version=11,platform=WINDOWS,maxInstances=10"
```
## Environment

OS: Linux (Docker but not OS dependant)
Browser: Does not matter
Browser version: No care
Browser Driver version: Havent even gotten to this point
Language Bindings version: Not even trying to run anything yet 
Selenium Grid version (if applicable): v.3.141.59
