### ISSUE TITLE
latest (3.141.59-zirconium) version of node cannot reach the node

### ISSUE THREAD

**Issue by burtsevyg** [SeleniumHQ/selenium#8065]
## 🐛 Bug Report

latest (3.141.59-zirconium) version of node cannot reach the node.
3.141.59-yttrium version work perfect.

## To Reproduce
Run docker stack:
(see instructions on https://dockerswarm.rocks/traefik/)
```
<!--
Please be sure to include an SSCCE (Short, Self Contained, Correct [compilable] example) http://sscce.org/
If you can't provide a link to the page, consider creating a reproducible page on https://jsfiddle.net/
-->

version: '3.7'

services:
  hub:
    image: selenium/hub:latest
    networks:
      - default
      - traefik-public
    deploy:
      labels:
        - traefik.frontend.rule=Host:selenium-${DOMAIN?Variable DOMAIN not set}
        - traefik.enable=true
        - traefik.port=4444
        - traefik.tags=${TRAEFIK_PUBLIC_TAG:-traefik-public}
        - traefik.docker.network=traefik-public
        # Traefik service that listens to HTTP
        - traefik.redirectorservice.frontend.entryPoints=http
        - traefik.redirectorservice.frontend.redirect.entryPoint=https
        # Traefik service that listens to HTTPS
        - traefik.webservice.frontend.entryPoints=https

  chrome:
    image: selenium/node-chrome:latest
    volumes:
      - /dev/shm:/dev/shm
    networks:
      - default
      - traefik-public
    environment:
      HUB_HOST: hub
      HUB_PORT: 4444
    deploy:
      mode: global
    entrypoint: bash -c 'SE_OPTS="-host $$HOSTNAME" /opt/bin/entry_point.sh'

networks:
  traefik-public:
    external: true
```
## Expected behavior

There are no error in the logs.

## Test script or set of commands reproducing this issue

Please, see reproduce section.

## Environment

OS:  docker 19.03.5
Browser:   latest (see docker-compose file)
Browser version:  latest (see docker-compose file)
Browser Driver version:  latest (see docker-compose file)
Language Bindings version:  latest (see docker-compose file)
Selenium Grid version (if applicable):  latest (see docker-compose file)
