### ISSUE TITLE
Support Default Capabilities for Nodes on Selenium 4

### ISSUE THREAD

**Issue by link89** [SeleniumHQ/selenium#8745]
## 🚀 Feature Proposal

Allow setting default capabilities on the side of the node.
This feature should work on both hub-nodes and standalone modes.

## Motivation

We need to run tests on different versions of chrome (stable, beta, canary). 

To do this we plan to set up 3 selenium-grid, each grid for one version.
Since they are installed in different paths, we have to specify the chrome binary on the client-side. Which is not convenient because they may be different on different machines.

To solve this problem I hope that I can set the default `chrome_binary` on the nodes' side so that I can just leave this field empty on the client-side and respect the configuration of nodes.

## Example

I plan to support this configuration via system properties when starting selenium service.

```bash
java -Dwebdriver.chrome.defaultCapabilities='{"browserName":"chrome","goog:chromeOptions":{"binary":"/path/to/chrome"}}' \
  -jar selenium-server-4.0.0-alpha-6.jar standalone
```

The preset capabilities will be merged with capabilities that send from client-side before starting a new webdriver session so that the client-side's capabilities always have higher priority than the server-side's.

**Comment by diemol** [comment]
An initial implementation has been done via https://github.com/SeleniumHQ/selenium/commit/d48a9596d868180b8b2da96e3c3118127365d434

It is possible now to provide a configuration that looks like this:
```toml
[node]
detect-drivers = false
[[node.driver-configuration]]
name = "Firefox Nightly"
stereotype = "{\"browserName\": \"firefox\", \"browserVersion\": \"86\", \"moz:firefoxOptions\": {\"binary\": \"/Applications/Firefox Nightly.app/Contents/MacOS/firefox-bin\"}}"
[[node.driver-configuration]]
name = "Chrome Beta"
stereotype = "{\"browserName\": \"chrome\", \"browserVersion\": \"88\", \"goog:chromeOptions\": {\"binary\": \"/Applications/Google Chrome Beta.app/Contents/MacOS/Google Chrome Beta\"}}"
[[node.driver-configuration]]
name = "Firefox"
stereotype = "{\"browserName\": \"firefox\", \"browserVersion\": \"84\"}"
[[node.driver-configuration]]
name = "Chrome"
stereotype = "{\"browserName\": \"chrome\", \"browserVersion\": \"87\"}"
```

and when the Node starts, you should see something like this:
```
20:49:45.250 INFO [NodeOptions.report] - Adding Chrome for {"browserName": "chrome","browserVersion": "87"} 12 times
20:49:45.253 INFO [NodeOptions.report] - Adding Firefox Nightly for {"browserName": "firefox","browserVersion": "86","moz:firefoxOptions": {"binary": "\u002fApplications\u002fFirefox Nightly.app\u002fContents\u002fMacOS\u002ffirefox-bin"}} 12 times
20:49:45.254 INFO [NodeOptions.report] - Adding Chrome Beta for {"browserName": "chrome","browserVersion": "88","goog:chromeOptions": {"binary": "\u002fApplications\u002fGoogle Chrome Beta.app\u002fContents\u002fMacOS\u002fGoogle Chrome Beta"}} 12 times
20:49:45.255 INFO [NodeOptions.report] - Adding Firefox for {"browserName": "firefox","browserVersion": "84"} 12 times
```

This will allow users to have more than one browser version on the Node, in the example above one can have Firefox Nightly (current 86), and the latest Firefox (currently 84) on the same Node. Same for Chrome. The browser options are merged with the capabilities sent by the user, where the user ones prevail over what is set on the Node. 

We will iterate on this based on feedback, and also try find a better way to let a user configure this. 

I am not sure when we will do the first Beta release, but we are doing every 2-3 weeks a prerelease to be used with the docker images, you can have a look [here](https://github.com/SeleniumHQ/docker-selenium/tree/beta-jars) in a few days and grab it from there. You could also build it from `trunk` as well.
