### ISSUE TITLE
ERROR [HashedWheelTimer.reportTooManyInstances] - You are creating too many HashedWheelTimer instances. HashedWheelTimer is a shared resource that must be reused across the JVM,so that only a few instances are created.

### ISSUE THREAD

**Issue by mcopjan** [SeleniumHQ/selenium#9112]
## 🐛 Bug Report
**4.0.0-beta-1-prerelease-20210114**
I have a grid4 with 20 chrome nodes (SE_NODE_MAX_CONCURRENT_SESSIONS=5), when running 50 (max) headless tests in parallel I can see hub dying with the error above. When I stopped execution I could see that the hub recovered after some time.

![image](https://user-images.githubusercontent.com/20699180/105994379-768dc080-609f-11eb-99fe-633d031747ee.png)

[selenium_hub_logs.txt.zip](https://github.com/SeleniumHQ/selenium/files/5880313/selenium_hub_logs.txt.zip)

```
version: '3.7'

services:

  hub:
    image: selenium/hub:4.0.0-beta-1-prerelease-20210114
    ports:
      - "4442:4442"
      - "4443:4443"
      - "4444:4444"
    deploy:
      placement:
        constraints:
          - node.role == manager
      restart_policy:
        condition: on-failure

  chrome:
    image: selenium/node-chrome:4.0.0-beta-1-prerelease-20210114
    volumes:
      - /dev/shm:/dev/shm
    depends_on:
      - hub
    environment:
      - SE_EVENT_BUS_HOST=hub
      - SE_EVENT_BUS_PUBLISH_PORT=4442
      - SE_EVENT_BUS_SUBSCRIBE_PORT=4443
      - LANG=en_GB.UTF-8
      - SE_NODE_MAX_CONCURRENT_SESSIONS=5
      - START_XVFB=false
      - SCREEN_WIDTH=1920
      - SCREEN_HEIGHT=1080
      - SCREEN_DEPTH=24
    entrypoint: bash -c 'SE_OPTS="--host $$HOSTNAME" /opt/bin/entry_point.sh'
    deploy:
      replicas: 20
      placement:
        constraints:
          - node.role == worker
      restart_policy:
        condition: on-failure


```
