### ISSUE TITLE
OPERA & EDGE desired capabilities no longer working in Python

### ISSUE THREAD

**Issue by domibarton** [SeleniumHQ/selenium#9275]
## 🐛 Bug Report

When using the `selenium.webdriver.common.desired_capabilities.OPERA` or `selenium.webdriver.common.desired_capabilities.EDGE` capability (constant) together with the official Selenium Docker images, you'll end up in a `KeyError: 'value'` exception!

## To Reproduce

1. Start Selenium Grid via Docker 
2. Run Selenium tests via Python bindings
3. Use `selenium.webdriver.common.desired_capabilities.OPERA` or `selenium.webdriver.common.desired_capabilities.EDGE`

## Expected behavior

The code should work and shouldn't end up in an exception like this:

```
Traceback (most recent call last):
  File "/tmp/selenium-error/tests/test.py", line 52, in <module>
    driver = Remote(desired_capabilities=DesiredCapabilities.OPERA)
  File "/tmp/selenium-error/.venv/lib/python3.9/site-packages/selenium/webdriver/remote/webdriver.py", line 157, in __init__
    self.start_session(capabilities, browser_profile)
  File "/tmp/selenium-error/.venv/lib/python3.9/site-packages/selenium/webdriver/remote/webdriver.py", line 252, in start_session
    response = self.execute(Command.NEW_SESSION, parameters)
  File "/tmp/selenium-error/.venv/lib/python3.9/site-packages/selenium/webdriver/remote/webdriver.py", line 321, in execute
    self.error_handler.check_response(response)
  File "/tmp/selenium-error/.venv/lib/python3.9/site-packages/selenium/webdriver/remote/errorhandler.py", line 127, in check_response
    value = value['value']
```

## Test script or set of commands reproducing this issue

Docker Compose:

```yaml
---
version: '3.8'

services:

  chrome:
    image: selenium/node-chrome:4.0.0-beta-2-prerelease-20210312
    volumes:
      - /dev/shm:/dev/shm
    depends_on:
      - selenium-hub
    environment:
      - SE_EVENT_BUS_HOST=selenium-hub
      - SE_EVENT_BUS_PUBLISH_PORT=4442
      - SE_EVENT_BUS_SUBSCRIBE_PORT=4443
    ports:
      - '5901:5900'

  firefox:
    image: selenium/node-firefox:4.0.0-beta-2-prerelease-20210312
    volumes:
      - /dev/shm:/dev/shm
    depends_on:
      - selenium-hub
    environment:
      - SE_EVENT_BUS_HOST=selenium-hub
      - SE_EVENT_BUS_PUBLISH_PORT=4442
      - SE_EVENT_BUS_SUBSCRIBE_PORT=4443
    ports:
      - '5902:5900'

  edge:
    image: selenium/node-edge:4.0.0-beta-2-prerelease-20210312
    volumes:
      - /dev/shm:/dev/shm
    depends_on:
      - selenium-hub
    environment:
      - SE_EVENT_BUS_HOST=selenium-hub
      - SE_EVENT_BUS_PUBLISH_PORT=4442
      - SE_EVENT_BUS_SUBSCRIBE_PORT=4443
    ports:
      - '5903:5900'

  opera:
    image: selenium/node-opera:4.0.0-beta-2-prerelease-20210312
    volumes:
      - /dev/shm:/dev/shm
    depends_on:
      - selenium-hub
    environment:
      - SE_EVENT_BUS_HOST=selenium-hub
      - SE_EVENT_BUS_PUBLISH_PORT=4442
      - SE_EVENT_BUS_SUBSCRIBE_PORT=4443
    ports:
      - '5904:5900'

  selenium-hub:
    image: selenium/hub:4.0.0-beta-2-prerelease-20210312
    container_name: selenium-hub
    ports:
      - '4442:4442'
      - '4443:4443'
      - '4444:4444'
```

Python Script:

```python
from selenium.webdriver import Remote
from selenium.webdriver.common.desired_capabilities import DesiredCapabilities


driver = Remote(desired_capabilities=DesiredCapabilities.OPERA)
driver.get('https://www.selenium.dev/')
driver.close()
```

## Environment

OS: Mac OS X.15
Browser: Edge / Opera
Browser version: `selenium/node-edge:4.0.0-beta-2-prerelease-20210312`
Browser Driver version: `selenium/node-edge:4.0.0-beta-2-prerelease-20210312`
Language Bindings version: Python `selenium==3.141.0`
Selenium Grid version (if applicable): `selenium/hub:4.0.0-beta-2-prerelease-20210312`
