### ISSUE TITLE
Selenium 4 k8s-deployment-full-grid.yaml not backward compatible with "/wd/hub"

### ISSUE THREAD

**Issue by josesa-xx** [SeleniumHQ/selenium#9287]
## 🐛 Bug Report

I've deployed [k8s-deployment-full-grid.yaml](https://github.com/SeleniumHQ/docker-selenium/blob/trunk/k8s-deployment-full-grid.yaml) in local cluster but my Selenium3 tests keep failing with error Message: "Unable to find handler for (POST) /wd/hub/session"

I suspect that is the kubernetes yaml file that is missing "selenium/hub".

## To Reproduce

Detailed steps to reproduce the behavior:
- deploy k8s-deployment-full-grid.yaml
- run Remote Web Driver test using url http://...host...:4444/wd/hub"

## Expected behavior

I would expect that the ".../wd/hub" default url as used until Selenium3 would continue to work for backward compatibility.

## Test script or set of commands reproducing this issue

Install kubernetes pods in dedicated namespace
```bash
# create namespace
kubectl create ns selenium

# Deploying all the grid components to kubernetes - 4.0.0-beta-2-prerelease-20210315
kubectl -n selenium apply -f https://raw.githubusercontent.com/SeleniumHQ/docker-selenium/trunk/k8s-deployment-full-grid.yaml

# Exposing the router
kubectl -n selenium expose deployment selenium-router-deployment --type=LoadBalancer --port=4444

# check status
curl -sS http://localhost:4444/status | jq -r '.value.ready'
```

Run test
```python
python3 -c '
from selenium import webdriver
firefox_options = webdriver.FirefoxOptions()
driver = webdriver.Remote(
    command_executor="http://localhost:4444/wd/hub",
    options=firefox_options
)
try:
  driver.get("http://www.google.com")
  driver.save_screenshot("./screenshot.png")
finally:
  driver.quit() 
'
```
Output:
```
Traceback (most recent call last):
  File "<string>", line 4, in <module>
  File "/home/user/.local/lib/python3.8/site-packages/selenium/webdriver/remote/webdriver.py", line 157, in __init__
    self.start_session(capabilities, browser_profile)
  File "/home/user/.local/lib/python3.8/site-packages/selenium/webdriver/remote/webdriver.py", line 252, in start_session
    response = self.execute(Command.NEW_SESSION, parameters)
  File "/home/user/.local/lib/python3.8/site-packages/selenium/webdriver/remote/webdriver.py", line 321, in execute
    self.error_handler.check_response(response)
  File "/home/user/.local/lib/python3.8/site-packages/selenium/webdriver/remote/errorhandler.py", line 242, in check_response
    raise exception_class(message, screen, stacktrace)
selenium.common.exceptions.WebDriverException: Message: Unable to find handler for (POST) /wd/hub/session
```

If I change the remote url to use instead "http://localhost:4444" test executes normally.

## Environment

OS: Windows 10, Docker Desktop with Kubernetes enabled
Browser: Firefox
Browser version: selenium/node-firefox:4.0.0-beta-2-prerelease-20210315

**Comment by josesa-xx** [comment]
Alternatively (for comparison) I also use a docker-compose version based on docker-compose-v3.yml where this also works:
```yaml
version: '3.5'

services:

  selenium-hub:
    image: selenium/hub:4.0.0-beta-2-prerelease-20210315 # selenium-4
    container_name: selenium-hub
    ports:
      - "4442:4442"
      - "4443:4443"
      - "4444:4444"
    healthcheck:
      test: /opt/bin/check-grid.sh
      interval: 30s
      timeout: 5s
      retries: 3
    restart: "always"

  chrome:
    image: selenium/node-chrome:4.0.0-beta-2-prerelease-20210315 # selenium-4
    shm_size: '1gb'
    depends_on:
      - selenium-hub
    environment:
      - SE_EVENT_BUS_HOST=selenium-hub
      - SE_EVENT_BUS_PUBLISH_PORT=4442
      - SE_EVENT_BUS_SUBSCRIBE_PORT=4443
    healthcheck:
      test: pgrep Xvfb
      interval: 30s
      timeout: 5s
      retries: 3
    restart: "always"

  firefox:
    image: selenium/node-firefox:4.0.0-beta-2-prerelease-20210315 # selenium-4
    shm_size: '1gb'
    depends_on:
      - selenium-hub
    environment:
      - SE_EVENT_BUS_HOST=selenium-hub
      - SE_EVENT_BUS_PUBLISH_PORT=4442
      - SE_EVENT_BUS_SUBSCRIBE_PORT=4443
    healthcheck:
      test: pgrep Xvfb
      interval: 30s
      timeout: 5s
      retries: 3
    restart: "always"
```
