### ISSUE TITLE
Copy the chromeOption video file and pass it to the Grid nodes

### ISSUE THREAD

**Issue by mohsenny** [SeleniumHQ/selenium#9500]
## 🐛 Bug Report

I initially brought this up in WebdriverIO's Github [issues](https://github.com/webdriverio/webdriverio/issues/6891), but both the wdio developer and I think this issue must be related to Selenium Grid rather than WebdriverIO

**Environment**
 - **WebdriverIO version:** `^6.10.5`
 - **Mode:** Running tests agaisnt 3 nodes in Selenium Grid
 - **Node.js version:** `v15.11.0`
 - **NPM version:** `7.6.0`
 - **Browser name and version:** `Chrome 99.0`
 - **Platform name and version:** My setup is in macOS, but running the tests in Linux Selenium nodes

**Config of WebdriverIO**
```
exports.config = {
    runner: 'local',
    hostname: 'localhost',
    port: 4444,
    path: '/wd/hub',
    headless: false,
    specs: [
        './test/specs/**/*.js'
    ],
    exclude: [
        // 'path/to/excluded/files'
    ],
    maxInstances: 3,
    capabilities: [{
        maxInstances: 3,
        browserName: 'chrome',
        acceptInsecureCerts: true,
        'goog:chromeOptions': {
          args: [
            '--use-fake-ui-for-media-stream', 
            '--use-fake-device-for-media-stream',
->          '--use-file-for-fake-video-capture=./video_1.y4m'
          ],
        }

    }],
    ....

```

**Describe the bug**
So here is the problem:

- When running the tests locally and 1 by 1 without involving Selenium grid, all the `goog:chromeOptions` options that I am passing (you can see above), are working and the webcam feed is showing the passed `video_1.y4m` video file:

<img width="954" alt="with feed" src="https://user-images.githubusercontent.com/1129811/119128150-8f96f480-ba35-11eb-87a9-123a84e939ce.png">

- However the exact test logic but this time running against 3 Selenium grid's nodes instead, results in the `goog:chromeOptions` not being passed, and therefore the passed video file won't be displayed:

<img width="936" alt="Screenshot 2021-05-21 at 12 26 02" src="https://user-images.githubusercontent.com/1129811/119129642-7abb6080-ba37-11eb-9f2e-3b32558f39e5.png">

**To Reproduce**
This is my `docker-compose` config that starts the Selenium Grid and 3 nodes:

```
version: "3"
services:
  chrome:
    image: selenium/node-chrome:4.0.0-beta-3-20210426
    volumes:
      - /dev/shm:/dev/shm
    depends_on:
      - selenium-hub
    scale: 3
    environment:
      - SE_EVENT_BUS_HOST=selenium-hub
      - SE_EVENT_BUS_PUBLISH_PORT=4442
      - SE_EVENT_BUS_SUBSCRIBE_PORT=4443
    ports:
      - "5900"

  selenium-hub:
    image: selenium/hub:4.0.0-beta-3-20210426
    container_name: selenium-hub
    ports:
      - "4442:4442"
      - "4443:4443"
      - "4444:4444"
```

**Expected behavior**
I would expect the chrome options to be passed to the Selenium grid the same way it works locally.
