### ISSUE TITLE
Grid router doesn't acknowledge the restart of chrome nodes 

### ISSUE THREAD

**Issue by yasha-dev1** [SeleniumHQ/selenium#9658]
## 🐛 Bug Report

Selenium Grid 4 is setup in K8s cluster. after some chrome nodes get restarted for any reason (the livenessprobe fails), the newly created ones get registered again and the number of available Processes are shown correctly but, the available sessions don't get deleted. (see below image)

![image](https://user-images.githubusercontent.com/58387199/125923819-051c75a3-6611-4e38-8d10-063d3531819a.png)

## To Reproduce

let some chrome nodes running in K8s. after some restarting some of the chrome node pods, the sessions shown in the grid router UI is hanged and considers them as processing. the sessions are considered to be processing in the router and won;t get stooped automatically(probably because It cannot find the IP of the session its running in, after pod restart in K8s, the IP of the pod changes) that's why the grid doesn't accept any new requests to process. 

## Expected behavior

after pod restart, different components of grid should acknowledge the downing of chrome node correctly and delete the mapping from the session, even though the IP of chrome node doesn't exist.

## Test script or set of commands reproducing this issue

Used the following K8s conf (newest version: 4.0.0-rc-1-prerelease-20210713)
Note: there are some custom livenessprobe added to _selenium-router_ and _selenium-chrome-node_ due to [the problem with selenium-router](https://github.com/SeleniumHQ/docker-selenium/issues/1318) and performance downgrade problem with chrome node.
```
# To execute this yml file use this command in your local kubernetes environment `kubectl apply -f k8s-deployment-full-grid.yaml`
#***************************************
#SELENIUM EVENT BUS
#***************************************
apiVersion: v1
kind: Service
metadata:
  name: selenium-event-bus
  labels:
    name: selenium-event-bus
    component: "selenium-grid-4"
spec:
  selector:
    app: selenium-event-bus
  ports:
    - name: port1
      protocol: TCP
      port: 4442
      targetPort: 4442
    - name: port2
      protocol: TCP
      port: 4443
      targetPort: 4443
    - name: port3
      protocol: TCP
      port: 5557
      targetPort: 5557

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: selenium-event-bus-deployment
  labels:
    app: selenium-event-bus
    name: selenium-event-bus
    component: "selenium-grid-4"
spec:
  replicas: 1
  selector:
    matchLabels:
      app: selenium-event-bus
  template:
    metadata:
      labels:
        app: selenium-event-bus
        name: selenium-event-bus
        component: "selenium-grid-4"
    spec:
      containers:
        - name: selenium-event-bus
          image: selenium/event-bus:4.0.0-rc-1-prerelease-20210713
          ports:
            - containerPort: 4442
              protocol: TCP
            - containerPort: 4443
              protocol: TCP
            - containerPort: 5557
              protocol: TCP
          livenessProbe:
            httpGet:
              path: /status
              port: 5557
            initialDelaySeconds: 5
            periodSeconds: 5
---
#***************************************
#SELENIUM SESSIONS MAP
#***************************************
apiVersion: v1
kind: Service
metadata:
  name: selenium-sessions
  labels:
    name: selenium-sessions
    component: "selenium-grid-4"
spec:
  selector:
    app: selenium-sessions
  ports:
    - name: port1
      protocol: TCP
      port: 5556
      targetPort: 5556

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: selenium-sessions-deployment
  labels:
    app: selenium-sessions
    name: selenium-sessions
    component: "selenium-grid-4"
spec:
  replicas: 1
  selector:
    matchLabels:
      app: selenium-sessions
  template:
    metadata:
      labels:
        app: selenium-sessions
        name: selenium-sessions
        component: "selenium-grid-4"
    spec:
      containers:
        - name: selenium-sessions
          image: selenium/sessions:4.0.0-rc-1-prerelease-20210713
          env:
            - name: SE_EVENT_BUS_HOST
              value: "selenium-event-bus"
            - name: SE_EVENT_BUS_PUBLISH_PORT
              value: "4442"
            - name: SE_EVENT_BUS_SUBSCRIBE_PORT
              value: "4443"
            - name: SE_OPTS
              value: "--log-level ALL"
          ports:
            - containerPort: 5556
              protocol: TCP
          livenessProbe:
            httpGet:
              path: /status
              port: 5556
            initialDelaySeconds: 5
            periodSeconds: 5

---
#***************************************
#SELENIUM SESSION QUEUE
#***************************************
apiVersion: v1
kind: Service
metadata:
  name: selenium-session-queue
  labels:
    name: selenium-session-queue
    component: "selenium-grid-4"
spec:
  selector:
    app: selenium-session-queue
  ports:
    - name: port1
      protocol: TCP
      port: 5559
      targetPort: 5559
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: selenium-session-queue-deployment
  labels:
    app: selenium-session-queue
    name: selenium-session-queue
    component: "selenium-grid-4"
spec:
  replicas: 1
  selector:
    matchLabels:
      app: selenium-session-queue
  template:
    metadata:
      labels:
        app: selenium-session-queue
        name: selenium-session-queue
        component: "selenium-grid-4"
    spec:
      containers:
        - name: selenium-session-queue
          image: selenium/session-queue:4.0.0-rc-1-prerelease-20210713
          env:
            - name: SE_EVENT_BUS_HOST
              value: "selenium-event-bus"
            - name: SE_EVENT_BUS_PUBLISH_PORT
              value: "4442"
            - name: SE_EVENT_BUS_SUBSCRIBE_PORT
              value: "4443"
            - name: SE_OPTS
              value: "--log-level ALL"
          ports:
            - containerPort: 5556
              protocol: TCP
          livenessProbe:
            httpGet:
              path: /status
              port: 5559
            initialDelaySeconds: 5
            periodSeconds: 5
---
#***************************************
#SELENIUM DISTRIBUTOR
#***************************************
apiVersion: v1
kind: Service
metadata:
  name: selenium-distributor
  labels:
    name: selenium-distributor
    component: "selenium-grid-4"
spec:
  selector:
    app: selenium-distributor
  ports:
    - name: port1
      protocol: TCP
      port: 5553
      targetPort: 5553

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: selenium-distributor-deployment
  labels:
    app: selenium-distributor
    name: selenium-distributor
    component: "selenium-grid-4"
spec:
  replicas: 1
  selector:
    matchLabels:
      app: selenium-distributor
  template:
    metadata:
      labels:
        app: selenium-distributor
        name: selenium-distributor
        component: "selenium-grid-4"
    spec:
      containers:
        - name: selenium-distributor
          image: selenium/distributor:4.0.0-rc-1-prerelease-20210713
          env:
            - name: SE_EVENT_BUS_HOST
              value: "selenium-event-bus"
            - name: SE_EVENT_BUS_PUBLISH_PORT
              value: "4442"
            - name: SE_EVENT_BUS_SUBSCRIBE_PORT
              value: "4443"
            - name: SE_SESSIONS_MAP_HOST
              value: "selenium-sessions"
            - name: SE_SESSIONS_MAP_PORT
              value: "5556"
            - name: SE_SESSION_QUEUE_HOST
              value: "selenium-session-queue"
            - name: SE_SESSION_QUEUE_PORT
              value: "5559"
            - name: SE_OPTS
              value: "--log-level ALL"
          ports:
            - containerPort: 5553
              protocol: TCP
          livenessProbe:
            httpGet:
              path: /status
              port: 5553
            initialDelaySeconds: 5
            periodSeconds: 5
---
#***************************************
#SELENIUM ROUTER
#***************************************
apiVersion: v1
kind: Service
metadata:
  name: selenium-router
  labels:
    name: selenium-router
    component: "selenium-grid-4"
spec:
  selector:
    app: selenium-router
  ports:
    - name: web
      protocol: TCP
      port: 4444
      targetPort: 4444

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: selenium-router-deployment
  labels:
    app: selenium-router
    name: selenium-router
    component: "selenium-grid-4"
spec:
  replicas: 1
  selector:
    matchLabels:
      app: selenium-router
  template:
    metadata:
      labels:
        app: selenium-router
        name: selenium-router
        component: "selenium-grid-4"
    spec:
      containers:
        - name: selenium-router
          image: selenium/router:4.0.0-rc-1-prerelease-20210713
          env:
            - name: SE_DISTRIBUTOR_HOST
              value: "selenium-distributor"
            - name: SE_DISTRIBUTOR_PORT
              value: "5553"
            - name: SE_SESSIONS_MAP_HOST
              value: "selenium-sessions"
            - name: SE_SESSIONS_MAP_PORT
              value: "5556"
            - name: SE_SESSION_QUEUE_HOST
              value: "selenium-session-queue"
            - name: SE_SESSION_QUEUE_PORT
              value: "5559"
            - name: SE_OPTS
              value: "--log-level ALL"

          ports:
            - containerPort: 4444
              protocol: TCP
          livenessProbe:
            exec:
              command:
                - /bin/sh
                - -c
                - |
                  curl -X POST -H "Content-Type: application/json" --data '{"query": "{ grid { } }"}' --max-time 5 http://localhost:4444/graphql
            initialDelaySeconds: 5
            periodSeconds: 5
---
#***************************************
#SELENIUM CHROME NODE
#***************************************
apiVersion: v1
kind: Service
metadata:
  name: selenium-chrome-node
  labels:
    name: selenium-chrome-node
    component: "selenium-grid-4"
spec:
  selector:
    app: selenium-chrome-node
  ports:
    - name: port1
      protocol: TCP
      port: 6900
      targetPort: 5900

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: selenium-chrome-node-deployment
  labels:
    app: selenium-chrome-node
    name: selenium-chrome-node
    component: "selenium-grid-4"
spec:
  replicas: 38
  selector:
    matchLabels:
      app: selenium-chrome-node
  template:
    metadata:
      labels:
        app: selenium-chrome-node
        name: selenium-chrome-node
        component: "selenium-grid-4"
    spec:
      containers:
        - name: selenium-chrome-node
          image: selenium/node-chrome:4.0.0-rc-1-prerelease-20210713
          env:
            - name: SE_EVENT_BUS_HOST
              value: "selenium-event-bus"
            - name: SE_EVENT_BUS_PUBLISH_PORT
              value: "4442"
            - name: SE_EVENT_BUS_SUBSCRIBE_PORT
              value: "4443"
            - name: SE_OPTS
              value: "--log /opt/selenium/logs.txt --log-level ALL"
          ports:
            - containerPort: 5553
              protocol: TCP
          livenessProbe:
            exec:
              command:
                - /bin/sh
                - -c
                - |
                  #!/bin/sh
                  curl localhost:5555/status
                  SELENIUM_LOG_PATH="/opt/selenium/logs.txt"

                  grep -Eo '[0-9]{19}' $SELENIUM_LOG_PATH | head -20 |
                  xargs -I {} bash -c 'if [ {} != 0000000000000000000 ]; then echo {}; fi' | head -1 | {
                    read timestamp;
                    randomNumber=$(awk -v min=1 -v max=60 'BEGIN{srand(); print int(min+rand()*(max-min+1))}')
                    timestamp_1=$((timestamp/1000000000))
                    timestamp_2=$((timestamp_1+3600+randomNumber))
                    currenttimestamp=$(date +%s)
                    if [ "$currenttimestamp" -gt "$timestamp_2" ]; then
                      echo "exiting with 1"
                      exit 1;
                    else
                      echo "exiting with 0"
                      exit 0;
                    fi
                  }

            initialDelaySeconds: 5
            periodSeconds: 5
          volumeMounts:
            - name: dshm
              mountPath: /dev/shm
          resources:
            requests:
              memory: "1Gi"
              cpu: "1"
            limits:
              memory: "1Gi"
              cpu: "1"
      volumes:
        - name: dshm
          emptyDir: { "medium": "Memory" }
```

## Environment

OS: docker image
Browser: Chrome
Selenium Grid version (if applicable): 4.0.0-rc-1-prerelease-20210713
