### ISSUE TITLE
[Docker] [MacOS m1] Chrome failed to start: crashed

### ISSUE THREAD

**Issue by Jeckerson** [SeleniumHQ/selenium#9733]
## 🐛 Bug Report

It is impossible to launch WebDriver via docker in MacOS. Tried everything that I could find and also tried different combinations it terms of docker configs and code execution... Something similar (in terms of crashes also occurs with Firefox).

**Same code works fine on Windows 10.**

```
WebDriverError: unknown error: Chrome failed to start: crashed.
  (unknown error: DevToolsActivePort file doesn't exist)
  (The process started from chrome location /usr/bin/google-chrome is no longer running, so ChromeDriver is assuming that Chrome has crashed.)
Build info: version: '3.141.59', revision: 'e82be7d358', time: '2018-11-14T08:25:53'
System info: host: 'selenium', ip: '172.22.0.4', os.name: 'Linux', os.arch: 'amd64', os.version: '5.10.25-linuxkit', java.version: '1.8.0_292'
Driver info: driver.version: unknown
remote stacktrace: #0 0x00400062aa63 <unknown>
#1 0x00400039f458 <unknown>
#2 0x0040003c22e3 <unknown>
#3 0x0040003bde9f <unknown>
#4 0x0040003f7b72 <unknown>
#5 0x0040003f1fd3 <unknown>
#6 0x0040003c8514 <unknown>
#7 0x0040003c9505 <unknown>
#8 0x004000656e2e <unknown>
#9 0x00400066c886 <unknown>
#10 0x004000657d75 <unknown>
#11 0x00400066dd94 <unknown>
#12 0x00400064e8eb <unknown>
#13 0x004000688cd8 <unknown>
#14 0x004000688e58 <unknown>
#15 0x0040006a2dfd <unknown>
#16 0x0040023b6609 start_thread

      at Object.checkLegacyResponse (node_modules/selenium-webdriver/lib/error.js:553:15)
      at parseHttpResponse (node_modules/selenium-webdriver/lib/http.js:634:13)
      at Executor.execute (node_modules/selenium-webdriver/lib/http.js:568:28)
      at processTicksAndRejections (internal/process/task_queues.js:95:5)
```

## To Reproduce

docker-compose.yml:
```yml
selenium:
    shm_size: '3gb'
    container_name: selenium
    hostname: selenium
    image: selenium/standalone-chrome-debug
    ports:
      - 4444:4444
      - 5900:5900

e2e:
    container_name: e2e
    hostname: e2e
    build: infrastructure/images/e2e
    working_dir: /srv
    environment:
      - SELENIUM_REMOTE_URL=http://selenium:4444/wd/hub
    volumes:
      - ./www/e2e:/srv
```

options.json
```json
[
    "--headless",
    "--no-sandbox",
    "--disable-gpu",
    "start-maximized",
    "--disable-extensions",
    "--incognito"
]
```

## Expected behavior

Test specs must execute.

## Test script or set of commands reproducing this issue

```javascript
(async() => {
    const driver = new Builder()
        .forBrowser("chrome")
        .setChromeOptions(chromeOptions)
        .build();
    
    driver.get("https://google.com");
})();
```

## Environment

OS: MacOS 11.5
Browser: Chrome
Browser version: 91
Browser Driver version: 92.0.4515.107
Language Bindings version: Javascript (4.0.0-beta.4)
Selenium Grid version (if applicable): latest
