### ISSUE TITLE
Atoms getText returns strange values with absolutely positioned elements

### ISSUE THREAD

**Issue by ar4development** [SeleniumHQ/selenium#9851]
## 🐛 Bug Report

When apply RelativeLocator.above() to a sample page, there is unexpected output produced. See below.

## To Reproduce

Detailed steps to reproduce the behavior:

Use this docker-compose to set up environment:

```yaml
version: '2'

services:

  chrome:
    image: selenium/node-chrome:4.0.0-rc-2-prerelease-20210916
    shm_size: 2gb
    depends_on:
      - selenium-hub
    environment:
      - SE_EVENT_BUS_HOST=selenium-hub
      - SE_EVENT_BUS_PUBLISH_PORT=4442
      - SE_EVENT_BUS_SUBSCRIBE_PORT=4443
    ports:
      - "6900:5900"
    volumes: 
      - ./site:/site    

  selenium-hub:
    image: selenium/hub:4.0.0-rc-2-prerelease-20210916
    ports:
      - "4442:4442"
      - "4443:4443"
      - "4444:4444"
```

Use this page:

```xml
<html>
 <head>
   <meta charset="utf-8"/>
 </head>
 <style>
    .c {
    	position: absolute;
    	border: 1px solid black;
    	height: 50px;
    	width: 50px;
    }
 </style>
 <body>
  <div style="position: relative;">
    <div id= "a" class="c" style="left:25;top:0;">El-A</div>
    <div id= "b" class="c" style="left:78;top:30;">El-B</div>
    <div id= "c" class="c" style="left:131;top:60;">El-C</div>
    <div id= "d" class="c" style="left:0;top:53;">El-D</div>
    <div id= "e" class="c" style="left:53;top:83;">El-E</div>
    <div id= "f" class="c" style="left:106;top:113;">El-F</div>
  </div>
 </body>
</html>
```

which is rendered as

![image](https://user-images.githubusercontent.com/66011915/133996949-581a2982-c416-44bf-a215-13be2f091a47.png)

Then use the code like:

```java
WebElement base = driver
        .findElement(By.id("e"));
List<WebElement> cells = driver
        .findElements(
                RelativeLocator
                        .with(By.tagName("div"))
                        .above(base));
cells
        .stream()
        .map(webElement -> webElement.getText())
        .forEach(System.out::println);
```

## Expected behavior

The output produced:

```
El-B
El-A
```
## Observed behavior:

The output produced:

```
El-B
El-A
El-A
El-B
El-C
El-D
El-E
El-F
```

## Environment

OS: Ubuntu 20.04
Browser: Chrome
Browser version: packaged to official selenium docker image
Browser Driver version: packaged to official selenium docker image
Language Bindings version: Java 4.0.0-rc-1
Selenium Grid version (if applicable): 4.0.0-rc-2
