### ISSUE TITLE
[🚀 Feature]:  v4 should support port -1 like v3

### ISSUE THREAD

**Issue by mattblaha** [SeleniumHQ/selenium#9940]
### Feature and motivation

In version 3, the -p option to node can be set to -1 and an unused port will be detected and used. This is really useful for testing locally, but also for rootless container setups like podman. As far as I can tell, this functionality does not exist in version 4.

### Usage example

For example, this snippet from a docker-compose.yml works very well with rootless containers on version 3:

```
version: "3"
services:
  selenium-hub:
    image: selenium/hub:3.141.59
    container_name: selenium-hub
    ports:
      - "127.0.0.1:4444:4444"

  chrome:
    image: selenium/node-chrome:3.141.59
    volumes:
      - /dev/shm:/dev/shm
    deploy:
      replicas: 4
    depends_on:
      - selenium-hub
    environment:
      - HUB_HOST=selenium-hub
      - HUB_PORT=4444
      - NODE_PORT=-1
```

With version 4, I need to specify each chrome service individually, or otherwise automate the port setting per instance (which doesn't work very well with docker-compose.)
