### ISSUE TITLE
[🐛 Bug]: Dynamic Grid: java.lang.reflect.InvocationTargetException

### ISSUE THREAD

**Issue by pmswatuser** [SeleniumHQ/selenium#9982]
### What happened?

Unable run grid in dynamic mode. Using compose file to run the services on the same docker host.

Docker version : Docker version 20.10.8, build 3967b7d
Docker host is Windows. 

Docker-compose content:

```yaml
version: "3"
services:
  node-docker:
    image: selenium/node-docker:4.0.0
    volumes:        
      - ./config.toml:/opt/bin/config.toml
      - ./assets:/opt/selenium/assets
    depends_on:
      - selenium-hub
    environment:
      - SE_EVENT_BUS_HOST=selenium-hub
      - SE_EVENT_BUS_PUBLISH_PORT=4442
      - SE_EVENT_BUS_SUBSCRIBE_PORT=4443

  selenium-hub:
    image: selenium/hub:4.0.0
    container_name: selenium-hub
    ports:
      - "4442:4442"
      - "4443:4443"
      - "4444:4444"
```

Config.toml with image tags:

```toml
[docker]
# Configs have a mapping between the Docker image to use and the capabilities that need to be matched to
# start a container with the given image.
configs = [
    "selenium/standalone-firefox:4.0.0", "{\"browserName\": \"firefox\"}",
    "selenium/standalone-chrome:4.0.0", "{\"browserName\": \"chrome\"}",
    "selenium/standalone-edge:4.0.0", "{\"browserName\": \"MicrosoftEdge\"}"
    ]

# URL for connecting to the docker daemon
# host.docker.internal works for macOS and Windows.
# Linux could use --net=host in the `docker run` instruction or 172.17.0.1 in the URI below.
# To have Docker listening through tcp on macOS, install socat and run the following command
# socat -4 TCP-LISTEN:2375,fork UNIX-CONNECT:/var/run/docker.sock
url = "http://host.docker.internal:2375"
# Docker imagee used for video recording
#video-image = "selenium/video:ffmpeg-4.3.1-20211013"

# Uncomment the following section if you are running the node on a separate VM
# Fill out the placeholders with appropriate values
#[server]
#host = "tcp://172.23.0.3"
#port = "2375"
```

### How can we reproduce the issue?

```shell
Use the provided compose file and toml file to run instances of the images. The grid is up and sessions are queued, but containers are not spun up in a dynamic fashion.
```

### Relevant log output

```shell
C:\Users\a149760\Desktop\Grid4>docker-compose -f elastic-grid.yml up
[+] Running 3/3
 - Network grid4_default          Created                                                                                                                                                                                               0.0s
 - Container selenium-hub         Created                                                                                                                                                                                               0.7s
 - Container grid4-node-docker-1  Created                                                                                                                                                                                               1.0s
Attaching to grid4-node-docker-1, selenium-hub
selenium-hub         | 2021-10-25 14:23:21,577 INFO Included extra file "/etc/supervisor/conf.d/selenium-grid-hub.conf" during parsing
selenium-hub         | 2021-10-25 14:23:21,579 INFO supervisord started with pid 9
grid4-node-docker-1  | 2021-10-25 14:23:22,567 INFO Included extra file "/etc/supervisor/conf.d/selenium-grid-node-docker.conf" during parsing
grid4-node-docker-1  | 2021-10-25 14:23:22,569 INFO supervisord started with pid 8
selenium-hub         | 2021-10-25 14:23:22,581 INFO spawned: 'selenium-grid-hub' with pid 11
selenium-hub         | 14:23:22.974 INFO [LoggingOptions.configureLogEncoding] - Using the system default encoding
selenium-hub         | 2021-10-25 14:23:22,976 INFO success: selenium-grid-hub entered RUNNING state, process has stayed up for > than 0 seconds (startsecs)
selenium-hub         | 14:23:22.979 INFO [OpenTelemetryTracer.createTracer] - Using OpenTelemetry for tracing
selenium-hub         | 14:23:23.052 INFO [BoundZmqEventBus.<init>] - XPUB binding to [binding to tcp://*:4442, advertising as tcp://172.27.0.2:4442], XSUB binding to [binding to tcp://*:4443, advertising as tcp://172.27.0.2:4443]
selenium-hub         | 14:23:23.103 INFO [UnboundZmqEventBus.<init>] - Connecting to tcp://172.27.0.2:4442 and tcp://172.27.0.2:4443
selenium-hub         | 14:23:23.122 INFO [UnboundZmqEventBus.<init>] - Sockets created
grid4-node-docker-1  | 2021-10-25 14:23:23,572 INFO spawned: 'selenium-grid-node-docker' with pid 10
grid4-node-docker-1  | Starting Selenium Grid Node Docker...
grid4-node-docker-1  | 2021-10-25 14:23:23,577 INFO success: selenium-grid-node-docker entered RUNNING state, process has stayed up for > than 0 seconds (startsecs)
grid4-node-docker-1  | 14:23:23.910 INFO [LoggingOptions.configureLogEncoding] - Using the system default encoding
grid4-node-docker-1  | 14:23:23.916 INFO [OpenTelemetryTracer.createTracer] - Using OpenTelemetry for tracing
grid4-node-docker-1  | 14:23:23.983 INFO [UnboundZmqEventBus.<init>] - Connecting to tcp://selenium-hub:4442 and tcp://selenium-hub:4443
grid4-node-docker-1  | 14:23:24.024 INFO [UnboundZmqEventBus.<init>] - Sockets created
selenium-hub         | 14:23:24.124 INFO [UnboundZmqEventBus.<init>] - Event bus ready
selenium-hub         | 14:23:24.725 INFO [Hub.execute] - Started Selenium Hub 4.0.0 (revision 3a21814679): http://172.27.0.2:4444
grid4-node-docker-1  | 14:23:25.026 INFO [UnboundZmqEventBus.<init>] - Event bus ready
grid4-node-docker-1  | 14:23:25.129 INFO [NodeServer.createHandlers] - Reporting self as: http://172.27.0.3:5555
grid4-node-docker-1  | 14:23:25.146 INFO [NodeOptions.getSessionFactories] - Detected 12 available processors
grid4-node-docker-1  | java.lang.reflect.InvocationTargetException
grid4-node-docker-1  |  at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
grid4-node-docker-1  |  at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
grid4-node-docker-1  |  at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
grid4-node-docker-1  |  at java.base/java.lang.reflect.Method.invoke(Method.java:566)
grid4-node-docker-1  |  at org.openqa.selenium.grid.Bootstrap.runMain(Bootstrap.java:77)
grid4-node-docker-1  |  at org.openqa.selenium.grid.Bootstrap.main(Bootstrap.java:70)
grid4-node-docker-1  | Caused by: org.openqa.selenium.grid.config.ConfigException: java.lang.reflect.InvocationTargetException
grid4-node-docker-1  |  at org.openqa.selenium.grid.config.MemoizedConfig.getClass(MemoizedConfig.java:115)
grid4-node-docker-1  |  at org.openqa.selenium.grid.node.config.NodeOptions.getNode(NodeOptions.java:131)
grid4-node-docker-1  |  at org.openqa.selenium.grid.node.httpd.NodeServer.createHandlers(NodeServer.java:128)
grid4-node-docker-1  |  at org.openqa.selenium.grid.node.httpd.NodeServer.asServer(NodeServer.java:184)
grid4-node-docker-1  |  at org.openqa.selenium.grid.node.httpd.NodeServer.execute(NodeServer.java:231)
grid4-node-docker-1  |  at org.openqa.selenium.grid.TemplateGridCommand.lambda$configure$4(TemplateGridCommand.java:129)
grid4-node-docker-1  |  at org.openqa.selenium.grid.Main.launch(Main.java:83)
grid4-node-docker-1  |  at org.openqa.selenium.grid.Main.go(Main.java:57)
grid4-node-docker-1  |  at org.openqa.selenium.grid.Main.main(Main.java:42)
grid4-node-docker-1  |  ... 6 more
grid4-node-docker-1  | Caused by: java.lang.reflect.InvocationTargetException
grid4-node-docker-1  |  at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
grid4-node-docker-1  |  at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
grid4-node-docker-1  |  at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
grid4-node-docker-1  |  at java.base/java.lang.reflect.Method.invoke(Method.java:566)
grid4-node-docker-1  |  at org.openqa.selenium.grid.config.ClassCreation.callCreateMethod(ClassCreation.java:50)
grid4-node-docker-1  |  at org.openqa.selenium.grid.config.MemoizedConfig.lambda$getClass$4(MemoizedConfig.java:100)
grid4-node-docker-1  |  at java.base/java.util.concurrent.ConcurrentHashMap.computeIfAbsent(ConcurrentHashMap.java:1737)
grid4-node-docker-1  |  at org.openqa.selenium.grid.config.MemoizedConfig.getClass(MemoizedConfig.java:95)
grid4-node-docker-1  |  ... 14 more
grid4-node-docker-1  | Caused by: org.openqa.selenium.docker.DockerException: Unable to reach the Docker daemon at http://host.docker.internal:2375
grid4-node-docker-1  |  at org.openqa.selenium.grid.node.docker.DockerOptions.getDockerSessionFactories(DockerOptions.java:125)
grid4-node-docker-1  |  at org.openqa.selenium.grid.node.local.LocalNodeFactory.create(LocalNodeFactory.java:80)
grid4-node-docker-1  |  ... 22 more
grid4-node-docker-1  | Exception in thread "Thread-0" java.lang.NullPointerException
grid4-node-docker-1  |  at org.openqa.selenium.grid.node.httpd.NodeServer.lambda$new$0(NodeServer.java:80)
grid4-node-docker-1  |  at java.base/java.lang.Thread.run(Thread.java:829)
grid4-node-docker-1  | 2021-10-25 14:23:38,163 INFO exited: selenium-grid-node-docker (exit status 1; not expected)
Gracefully stopping... (press Ctrl+C again to force)
[+] Running 0/1
 - Container grid4-node-docker-1  Stopping                                                                                                                                                                                              0.2s
[+] Running 2/2
 - Container selenium-hub         Killed                                                                                                                                                                                                0.5s
 - Container grid4-node-docker-1  Killed                                                                                                                                                                                                0.5s
canceled
```

### Operating System

Windows 10

### Selenium version

3.14 using Java and testNG from Eclipse

### What are the browser(s) and version(s) where you see this issue?

chrome and FF capabilities (options)

### What are the browser driver(s) and version(s) where you see this issue?

N/A

### Are you using Selenium Grid?

4.0.0
